### ISSUE TITLE
[Data Model] Request#rating#priceSpecificationRef: what is it? what type?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#101]
I don't understand the purpose of priceSpecification and especially Rating#priceSpecificationRef. This seems to be a reference to an object of type PriceSpecification but has type String. (and I don't see any class PriceSpecification). Any help on this? Is this a mistake?

```turtle
###  https://onerecord.iata.org/Ratings#priceSpecification
ratings:priceSpecification rdf:type owl:DatatypeProperty ;
                 rdfs:domain :Ratings ;
                 rdfs:range xsd:string ;
                 rdfs:comment "Specification of the price e.g. Street, Group, Spot, etc."@en ;
                 rdfs:label "ratings:priceSpecification"@en .

###  https://onerecord.iata.org/Ratings#priceSpecificationRef
ratings:priceSpecificationRef rdf:type owl:DatatypeProperty ;
                 rdfs:domain :Ratings ;
                 rdfs:range xsd:string ;
                 rdfs:comment "Reference of price specifications"@en ;
                 rdfs:label "ratings:priceSpecificationRef"@en .
```

**Comment by lambertciata** [comment]
Hello,
In the distribution part of the data model, the priceSpecification indicates if the price proposed is Street price, Group price, etc... It is a string.
The reference is used to indicate the reference if relevant (e.g. the agreement reference if existing)
