### ISSUE TITLE
[API] Impossible to know the revision number of a LO

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#104]
The API specification mentions that a LO must have a revision number. This revision number should be passed when patching this LO to ensure the patch is being proposed on the latest revision of the LO.

But How do I know this revision number? If I GET a LO it does not have a revision among its properties, which I think is normal because it would introduce a technical value that has nothing to do with other values. 
The only class having this revision in the current specification is the PatchRequest. I think the AuditTrail of a LO should carry this revision. So that if we need to patch a LO, we need to get its auditTrail before, and know its revision number.

Another solution would be to include the revision of a LO in a header.

@andrablaj any thoughts?

**Comment by andrablaj** [comment]
I have added a `latestRevision `field to AuditTrail, and a return header` Latest-Revision` when performing `GET `LO.
