### ISSUE TITLE
[API] The naming of properties that are collections should be plural

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#105]
The API ontology (@andrablaj ) has a bad naming of some properties which does not help to understand their purpose. Especially lists that should always be plural : 

- AuditTrail#changeRequest is a Set so should be named changeRequests
- In many classes of the API ontology there is a `error` property that is a Set of Errors => so it should be named `errors` (AudiTrail#error, Subscription#error, etc.)
- DelegationRequest#targetLogisticsObject => targetLogisticsObjects. Also the description of this property should be plural: "Identifier of the logistics object to which the access is requested"
- DelegationRequest#targetCompany => targetCompanies
- Subscription#contentType is a Set<String>. either use contentTypes or String contentType. I think there is a mistake here (only one content type or a list?)

**Comment by andrablaj** [comment]
Corrected field names [here](https://github.com/IATA-Cargo/ONE-Record/commit/60c34bf1cd83eb97026f6240064df565ca9ad2b6)
