### ISSUE TITLE
[Data Model] Impossible to book a flight that has multiple legs

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#106]
In the current model (from November), a BookingOptionRequest has BookingOptions.
I understand that:
- When a Shipper needs to send some goods, a Shipment and related objects are initialized, as well as a BookingOptionRequest having one TransportSegment from departure to destination.
- A forwarder will then propose different options:
  - one direct, airfreight only: so creates a BookingOptionRequest with requestType=Booking and link one BookingOption to it for the direct flight of a Carrier.
  - on indirect, airfreight only but with 2 legs, operated by the same company, same aircraft: the forwarder creates another BookingOptionRequest with one BookingOption also but this BookingOption needs to have 2 legs, but only 1 waybill. However the relationship between BookingOption and TransportSegment is 1:1... should it be 1:n? Did I miss something that could allow me create data of a flight having a connection?

**Comment by lambertciata** [comment]
It seems the same issue as #89

**Comment by grichka** [comment]
You're right
