### ISSUE TITLE
[API] Inconsistent Notification and LogisticsObjectRef specification

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#108]
- When a ONE Record server sends a Notification it is specified that:
  - The Client Subscription API:
   ```text
    The Client Subscription API:
        • ...
        • MUST respond with a 2XX response when it receives the Logistics Object.   
    ```
    - However a bit further in the document: `Response 204 Notification received successfully` 
 

  - `If the subscriber chose to receive the entire logistics object body via sendLogisticsObjectBody=true field, then the whole object is sent.`

  ```json
  {
    "@language": "en",
    "@type": [
      "https://onerecord.iata.org/Notification"
    ],
    "https://onerecord.iata.org/Notification#eventType": "OBJECT_CREATED",
    "https://onerecord.iata.org/Notification#logisticsObjectRef": {
      "@type": [
        "https://onerecord.iata.org/LogisticsObjectRef"
      ],
      "https://onerecord.iata.org/LogisticsObjectRef#logisticsObjectId": "someId",
      "https://onerecord.iata.org/LogisticsObjectRef#logisticsObjectType": " https://onerecord.iata.org/WayBill"
    },  
  "https://onerecord.iata.org/Notification#topic": " https://onerecord.iata.org/WayBill"
  }
   ```

  - `Where: logisticsObjectRef   Logistics Object for which the notification is sent

-------

So I think Notification cannot contain a logisticsObjectRef because a Notification can include the only the serialized URI of a LO or, in the case the party that has subscribed has defined `sendLogisticsObjectBody=true`, the Notification includes the LO with all its properties and values.

**My proposal :** 
- Do not use LogisticsObjectRef and do not use strings that should be URIs of LOs, because it is not correct as ONE Record should rely on **LinkedData principles**. LogisticsObjectRef should be simply replaced by LogisticsObject.
- This way, we keep the type, the structure, the semantics, everything about the LO, and if only its URI should be serialized of if all fields should, it is only a convention that should be documented.

(@andrablaj)

**Comment by IATA-Cargo** [comment]
Corrected type to `LogisticsObject `[here](https://github.com/IATA-Cargo/ONE-Record/commit/60c34bf1cd83eb97026f6240064df565ca9ad2b6).
