### ISSUE TITLE
[Data Model] BookingOptions and TransportSegments must be ordered

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#109]
If transportation is from point A to point D by B and C (A => B => C => D), we should be able to easily know the order of BookingOptions of a BookingRequest (their index in the "logistics plan").

Same for TransportSegments of a BookingOption if the cardinality 1:1 is changed to 1:n (see previous issue).

If the solution is to sort BookingOption by departureDate of their transportMovement(s) then I think it is not acceptable. 

I think the best solution should be to use a **RDF Sequence** instead of an unorderder collection as specified in the Ontology.
This may also apply to Waybill#containedWaybill(s)

**Comment by lambertciata** [comment]
This topic has been discussed among the group, it has been decided to not use a sequence as movements can be sorted out by departure dates and locations.

**Comment by grichka** [comment]
Ok, this makes sense
