### ISSUE TITLE
[Data Model] Ontology from November cannot be used by JOPA

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#110]
I tried to generate Java classes with JOPA and the newly published Ontology. I encountered some problems: 

- invalid unicode character

![image](https://user-images.githubusercontent.com/1225647/110636426-86271b80-81ac-11eb-812b-367e77a2a4eb.png)

- `PieceDg.java:[91,31] getDgDeclaration() in com.geodis.cdl.toto.model.PieceDg cannot override getDgDeclaration() i
n com.geodis.cdl.toto.model.Piece`. Indeed, dgDeclaration is defined at Piece level and at PieceDg level. I guess the dgDeclaration makes no sense at Piece level but only at PieceDg level?

----

Here is what I had to change in the ontology to be able to load it:

- Delete these lines (789-796)
- 
```turtle
###  https://onerecord.iata.org/Piece#dgDeclaration
piece:dgDeclaration rdf:type owl:ObjectProperty ;
                    rdfs:domain :Piece ;
                    rdfs:range :DgDeclaration ;
                    rdfs:comment "Reference to the Dangerous Goods declaration"@en ;
                    rdfs:label "piece:dgDeclaration"@en .
```

- Piece -> PieceDg line 5318
```turtle
[ rdf:type owl:Axiom ;
   owl:annotatedSource :PieceDg;
   owl:annotatedProperty rdfs:subClassOf ;
   owl:annotatedTarget [ rdf:type owl:Restriction ;
                         owl:onProperty piece:dgDeclaration ;
                         owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
                         owl:onClass :DgDeclaration
                       ] ;
   owl:deprecated "true"^^xsd:boolean
 ] .
```

- Change ... copy paste non-unicode characteur to three dots on line 2847

```turtle
###  https://onerecord.iata.org/Price#carrierChargeCode
price:carrierChargeCode rdf:type owl:DatatypeProperty ;
                        rdfs:domain :Price ;
                        rdfs:range xsd:string ;
                        rdfs:comment "Charge code for carrier, eg. CA, CB, ..."@en ;
                        rdfs:label "price:carrierChargeCode"@en .
```

**Comment by lambertciata** [comment]
Thanks for the quick feedback on the new version of the ontology.

- I will update the "..."
- Indeed DgDeclaration has been moved from Piece to PieceDg. The object property on Piece will be annotated as deprecated but not deleted for backward compatibility (they will be removed for next major version though).

**Comment by grichka** [comment]
Ok thanks.
So the Ontology won't be suitable to be used by technical tools we used so far to facilitate a bit the implementation 😞

**Comment by lambertciata** [comment]
I think we need to discuss that further :)

**Comment by mskopp** [comment]
We tries the same as @grichka today with the 2020-NOV Ontology and stumbled into the same problem.

Point it, updating the Ontology on the IATA-Cargo/one-record-server project will break the reference implementation:
It will no longer compile due to the "PieceDg cannot override getDgDeclaration()" error in Java!

One cannot keep this as "deprecated" in the IATA-Cargo/one-record-server implementation due to technical conflicts!

Also IATA-Cargo/one-record-server desperately needs a Ontology refresh.

**Comment by andrablaj** [comment]
Hi all! A new version of the ontology has been added [here](https://github.com/IATA-Cargo/ONE-Record/commit/db1d99495eda5c54b0974d7c58535759a43f3105). The JOPA/Java errors should be fixed now.
