### ISSUE TITLE
[Data Model] Add support for IATA direct shipments

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#111]
An official IATA Air Waybill is either a Consolidation or a Direct AWB.

This is also reflected in CargoXML XFWB3 as per `Waybill->BusinessHeaderDocument->IncludedHeaderNote->Content` which contains either `Direct Shipment` or `Consolidation Shipment`.

Ontology only supports `House` (of course for House Waybills) and `Master` but misses `Direct` in `waybill:waybillType` ontology definition.

The change to the Ontology would be the following - we could also provide a Pull Request.

    diff --git a/working_draft/ontology/IATA-1R-DM-Ontology-Nov2020.ttl b/working_draft/ontology/IATA-1R-DM-Ontology-Nov2020.ttl
    index fd83fc3..b838b2d 100644
    --- a/working_draft/ontology/IATA-1R-DM-Ontology-Nov2020.ttl
    +++ b/working_draft/ontology/IATA-1R-DM-Ontology-Nov2020.ttl
    @@ -3802,10 +3802,13 @@ waybill:waybillType rdf:type owl:DatatypeProperty ;
             rdfs:domain :Waybill ;
             rdfs:range [ rdf:type rdfs:Datatype ;
                          owl:oneOf [ rdf:type rdf:List ;
    -                                 rdf:first "House" ;
    +                                 rdf:first "Direct" ;
                                      rdf:rest [ rdf:type rdf:List ;
    -                                            rdf:first "Master" ;
    -                                            rdf:rest rdf:nil
    +                                            rdf:first "House" ;
    +                                            rdf:rest [ rdf:type rdf:List ;
    +                                                       rdf:first "Master" ;
    +                                                       rdf:rest rdf:nil
    +                                                     ]
                                               ]
                                    ]
                        ] ;

**Comment by lambertciata** [comment]
Hi, thanks for this feedback, indeed the enum can be enhanced. Will put that in the basket of modifications to bring for next iteration of the ontology.
