### ISSUE TITLE
[Data Model] Where to put data from AWB "other charges" and prepaid/collect "charge summary" fields and the currency?

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#116]
we are currently working on mapping the AWB to 1R and are having problems to map the OtherCharges and ChargeSummary data fields.

The 2020-Nov.xlsx recommends to put OtherCharges (which is plural!) into Ratings.
Point is, despite the "s", Ratings is singular. It's only one Rating, e.g. there is only one field "chargeCode" in Ratings.

Rating(s) seems to be the right place, it has
* chargeCode: enum e.g. MY / SC
* chargePaymentType: string e.g. P / C
nevertheless it is missing the "due Carrier/due Agent" entitlement flag.

The IATA-1R-DM-Logical-Data-Model-vCOTB-Nov2020.pdf shows a 1:n relationship between "Price" and "Rating(s)" but in the ontology it tells

price:ratings max 1 Ratings

There are multiple OtherCharges to map!
Also there is only 1 Price for a BookingOption/Booking.

I do not see *any* option to have a Set of Rating(s) available to place the various OtherCharges.

Could you please help where to put the multiple OtherCharges prepaid/collect plus due agent/carrier?

**Comment by mskopp** [comment]
I checked https://github.com/IATA-Cargo/ONE-Record/tree/master/June-2021-standard-forCOTBendorsement and still cannot see where to put the multiple charges from a (X)FWB.

**Comment by mskopp** [comment]
Okay, the Ontology draft for v1.1 got updated, so now we can have multiple "ratings" which allows to produce the following in a XFWB to 1R mapping. See following example:
```
    "https://onerecord.iata.org/BookingOption#price" : {
      "ratings" : [ {
        "ranges" : [ {
          "amount" : 3.11,
          "maximumQuantity" : 37.0,
          "minimumQuantity" : 37.0,
          "rateClassCode" : "Q",
          "unitBasis" : "KGM",
          "@type" : [ "https://onerecord.iata.org/Ranges" ]
        } ],
        "chargeType" : "Freight",
        "subTotal" : 115.07,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      }, {
        "chargeCode" : "RAC",
        "chargePaymentType" : [ "P" ],
        "chargeType" : "Surcharge",
        "subTotal" : 100.0,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      }, {
        "chargeCode" : "CDA",
        "chargePaymentType" : [ "P" ],
        "chargeType" : "Surcharge",
        "subTotal" : 105.82,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      }, {
        "chargePaymentType" : [ "P" ],
        "chargeType" : "WeightChargeTotalAmount",
        "subTotal" : 115.07,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      }, {
        "chargePaymentType" : [ "P" ],
        "chargeType" : "TaxTotalAmount",
        "subTotal" : 0.0,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      }, {
        "chargePaymentType" : [ "P" ],
        "chargeType" : "AgentTotalDuePayableAmount",
        "subTotal" : 105.82,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      }, {
        "chargePaymentType" : [ "P" ],
        "chargeType" : "CarrierTotalDuePayableAmount",
        "subTotal" : 100.0,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      }, {
        "chargePaymentType" : [ "P" ],
        "chargeType" : "GrandTotalAmount",
        "subTotal" : 320.89,
        "@type" : [ "https://onerecord.iata.org/Ratings" ]
      } ],
      "@type" : [ "https://onerecord.iata.org/Price" ]
    },

```
Still there are some uncertainties how to handle this the best way:

1. XFWB has a quality rate ("Q") for 37kg with a rate of 3.11 per Kg. We didn't found a field for the currency. We didn't found one single field for the quantity of 37Kg so we filled minimumQuantity *and* maximumQuantity.
2. Then we added 2 other charges, "RAC" and "CDA". Since there is no "due" in Ratings, we combined the ChargeCode with the "Due" (aka EntitlementCode), like it is also done in CIMP FWB already. Nevertheless, maybe a "due" property makes sense.
3. For Prepaid Charge Summary and Collect Charge Summary (FWB Segments 14+15), we added Ratings with chargeTypes "WeightChargeTotalAmount", "TaxTotalAmount", "AgentTotalDuePayableAmount", "CarrierTotalDuePayableAmount", "GrandTotalAmount". Not sure this is the right way to handle it. Nevertheless, if in future we also need to convert from ONERecord to XFWB, then these values are required to be filled in the (X)FWB.

**Comment by lambertciata** [comment]
Hi Martin, 
I started looking at this issue and have a few comments.

In your example where do the chargeCodes come from? I don't see them in Code List 1.1 or Code List 1.2.

1. I'm not 100% sure that we have covered the Quantity use case. The `Minimum `and `Maximum `quantity are to be used (optional) to define if there is a range where the rating is applicable. In your use case that would be for example if the rate 3.11/kg is applicable for weights between 1kg and 100kg. Shouldn't the 37kg information come from the shipment/piece in this case? Then question remains on where the calculated rating 37*3.11 is recorded, if it is.

2. We may be missing an `entitlement` field in the Ratings for that purpose (referring to Code List 1.3)

3. In current and original design of the data model, any field that is _only_ the sum of other fields is not directly added. Meaning that WeightChargeTotalAmount should be, outside of ONE Record, calculated based on all the charges declared. My understanding is that for Weight, there should be 1 or multiple ratings with `chargeCode `= XE that stands for weight. I believe GrandTotalAmount should be `grandTotal `field on Price object.

4. Indeed we lost the currency/unit when amounts were changed to double instead of Value. Might make sense to revert back to Value as units can be different (taking your example of "per kg")

Happy to discuss further

**Comment by mskopp** [comment]
> where do the chargeCodes come from?

Example: "chargeCode" : "RAC"
Since we didn't found any field for `entitlement`, we combined `Other Charge Code`, Data Element 504 aka Code List 1.2 and `Entitlement Code`, Data Element 315 aka Code List 1.3 (=basically `C` or `A`). 
**The major purpose here was to not loose the entitlement information**. 
I am not happy with this but it seemed to be the only workaround possible. So "RAC" is `RA` for `Dangerous Goods Fee` from due `C`arrier. And "chargeCode" : "CDA" is `Clearance and Handling — Destination` due `A`gent.


> I'm not 100% sure that we have covered the Quantity use case

Well I am not deep into all aspects of TACT Rules and which different ways exist to calculate a rate. Nevertheless I was under the impression that the total piece weight could possibly split into multiple rating lines (e.g. with having different ULD rates for different ULDs) and those single ratings might have different chargable weights which could be different from the piece net or gross weight.. Well actually I expected that there should be a quantity in the Range - simply because RANGES is **multiple** and therefore technically cannot implicitly relate to **one** "shipment/piece".


> We may be missing an entitlement field in the Ratings

Right.. adding this will result in chargeCode being free again to use Code List 1.2


>  any field that is only the sum of other fields is not directly added

Okay.. well in that case maybe the Ontology should clearly state which of all these important fields on the AWB (like WeightChargeTotalAmount, TaxTotalAmount..) , should be the sum of which other elements.
I remember cases where this has not been clear, especially because the AWB sometimes does not include all these details as single values. 
Also the sum for CarrierTotalDuePayableAmount sounds more or less clear, but for TaxTotalAmount normally there is no list of single Tax elements in a AWB.
I am not sure the pure AWB-to-1R conversion could be done using the strategy you proposed.


> there should be 1 or multiple ratings with chargeCode = XE that stands for weight

I am not 100% sure this is how it is specified today!
Point is, XE is a Code from 1.2 and 1.2 is for **OTHER** charges.
I have not seen any AWB (Paper, PDF, FWB, XFWB, you name it) where the "normal" weight charge is declared in the OtherCharges Segment with code "XE".
If this is the way to go then I am sure this is a major deviation from the current way of AWB usage!
Would be great to have an explicit documentation especially for the so called "airfreight" Rate.
(Just note there might be special explicit *other* charges with XE, maybe additional extra weight special charges. If you re-use the code 'XE' now for non-other charges, then you basically destroy this usage/option)


On https://onerecord.riege.com/ you could download an example XFWB which covers most of the above problem.
It might be helpful if you download it, convert it with that tool and then modify the JSON result in a way that we can easily see your proposed solutions.

Thanks,

**Comment by lambertciata** [comment]
Decision from last wokshop:

- Changes discussed above will be made to the next release of the model

**Comment by mskopp** [comment]
Hello Christophe,

as per discussion in the issue at https://github.com/IATA-Cargo/ONE-Record/issues/116#issuecomment-937658795
and with your commit at
https://github.com/IATA-Cargo/ONE-Record/commit/e0ef638c71124692e0f292a16b335ae06d92cdd9

I see the following changes:

* you added ratings:billingChargeIdentifier referring to CargoXML Code List 1.33 which allows to add total-other-charges-due-agent, total-other-charges-due-carrier, total-weight-charge… fine with that.
* you added a comment to have ratings:chargeCode referring to CargoXML Code List 1.1
* you added a new fields ratings:otherChargeCode referring to CargoXML Code List 1.2
* you didn't added an entitlement field, which is still required!
* you didn't added the quantity field in Rating as mentioned in #116

Best regards,
Martin

**Comment by lambertciata** [comment]
Hi @mskopp ,

entitlement and quantity will be added

Cheers
Chrsitophe
