### ISSUE TITLE
[CargoXML:1R mapping] Enhance quality and precision in data field mapping

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#117]
IATA-1R-DM-Logical-Data-Model-vCOTB-Nov2020.xlsx in sheet "AirWaybill" in row 50/51 recommends to map "Prepaid valuation charge" and "Prepaid Tax" to "in Ratings". First of all, it's 2 elements for "in Ratings", but "Ratings" itself is singular. 

And the entry in the "D" column is unprecise when e.g. compared to row 2, which e.g. tells "in Waybill/waybillPrefix". This us  much more precise because it mentions the field (not only the class) explicitly as Waybill:_waybillPrefix_.

In general, the "D" column should
* contain the full path of objects/classes
* not mix multiple fields in one row
* show 1:n relationships where required/possible
* if there are n entries available in the 1R domain, a selector should be used to indicate which of the n entries is the relevant (e.g. by tell a unique code/type to use)

For the above two elements for "in Ratings", it should clearly defined how they map to Ratings and how they are able to distinguish them from each other. Any 3rd party "reading" the data must be able to identify and distinguish the "Prepaid valuation charge" and the "Prepaid Tax" - probably they get a special code into a "ratingCode" or "ratingType" field or else. Any list of codes/types for such purpose should be available, the code to use should be part of the mapping mentioned in the XLSX/mapping description.

Example: for row 12, for Issuing Carrier's Agent name and city the XLSX tells "in Company details of Carrier's agent". I would prefer to have this split into two rows and be more precise e.g. like
* Issuing Carrier's Agent name -> waybill:bookingRef:freightForwarder:branch:branchName
* Issuing Carrier's Agent city -> waybill:bookingRef:freightForwarder:branch:location:address:cityName

(Note that this example does not include changes from #86)

**Comment by lambertciata** [comment]
We are not using the excel sheet anymore, everything has been shifted to the ontology.
