### ISSUE TITLE
[Data Model] How to link a Logistic Object to IotDevice?

### ISSUE THREAD

**Issue by victsang001** [IATA-Cargo/ONE-Record#119]
The data model below mentions that Logistic Object(e.g. Piece, ULD, Location) can have many IotDevices.

![image](https://user-images.githubusercontent.com/73921302/114995212-2a992d80-9ed0-11eb-91d0-350edd6ec506.png)

But I can't find the data property inside a LO to link to the IotDevice object. For example, the ULD class below has no property point to the IotDevice. 
![image](https://user-images.githubusercontent.com/73921302/114996354-52d55c00-9ed1-11eb-893e-4b0f5e2446cc.png)

Could you let me know how to solve this problem?  Thanks!

**Comment by lambertciata** [comment]
Hi,

Thanks for your feedback, indeed all Logistic Objects (LO) can be linked to multiple IotDevices. This means that each LO needs to have a data property `iotDevices` that is an array of IotDevices. This is not explicitly described in the XLS version of the data model, that could be added on the next release for more clarification (it will be added on Logistic Object class in the ontology directly).

Thanks
Christophe

**Comment by victsang001** [comment]
Dear Christophe,

Many thanks!

May I know the schedule for next release?


Best Regards,
Vic

**Comment by lambertciata** [comment]
A couple of issue are being discussed but next release should be ready in the next weeks.

Thanks
Christophe

**Comment by GLSHK-Barry** [comment]
Hi Christophe,

May I know where could be found the updated release?

Thanks
Barry

**Comment by lambertciata** [comment]
Hi,

Sorry for the very late feedback, the latest version is available on Github [here](https://github.com/IATA-Cargo/ONE-Record/blob/master/June-2021-standard-COTB-endorsed/Data-Model/IATA-1R-DM-Ontology-vCOTB-Jun2021.ttl).

Cheers
