### ISSUE TITLE
OntOlogy Pitfall Scanner - results

### ISSUE THREAD

**Issue by riannella** [IATA-Cargo/ONE-Record#121]
Hi, I used the OOPS service too review the Cargo ontology and found a few issues that it raised.

NOTE: The OOPS service is having some problems apparently (I was in contact with the developer) in accessing online ontologies and can only accept XML pasted text.

Attached is a copy of the output from OOPS (the developer sent this to me)

There are a number of important and minor suggestions it makes...and one critical

This may be useful for any future updates of the ontology

[cargo Ontology OOPS.zip](https://github.com/IATA-Cargo/ONE-Record/files/6362216/cargo.Ontology.OOPS.zip)

**Comment by andrablaj** [comment]
Hi! Thank you for the info, this is very helpful. The ONE Record Data Model experts were notified and they are going to look into it.

**Comment by riannella** [comment]
Great, let me know if you need any external reviewers 👍

**Comment by lambertciata** [comment]
Hi @riannella we have the new version available [here](https://github.com/IATA-Cargo/ONE-Record/blob/master/June-2021-standard-COTB-endorsed/Data-Model/IATA-1R-DM-Ontology-vCOTB-Jun2021.ttl), if you want to review it with OOPS you are more than welcome!
