### ISSUE TITLE
[Mapping Question] FMA/FNA handling

### ISSUE THREAD

**Issue by GLSHK-Barry** [IATA-Cargo/ONE-Record#122]
Most of the  data exchange is using CargoIMP, may I know
- How to handle FMA/FNA on 1R? e.g. Forwarder submit a shipment to airline, then airline reply FNA would not in sync
- Which LO could be used on mapping?

Please advise.
Thanks a lot.

**Comment by lambertciata** [comment]
Hi,

From my understanding FMA and FNA messages are very specific to messaging and the equivalent in 1R may not be as straightfoward, if it is necessary. Below my point of view:

- FMA: It depends on the use case/context and what exists. It could be directly part of the API response, could be the update of a specific field (e.g. "booking pending" on BookingOption), could be an Event associated to the proper LO.
- FNA: I believe it should be part of the API response or could be an Event associated to the proper LO (given by the context)

Hope that clarifies 
Christophe
