### ISSUE TITLE
Should Request be marked as deprecated as there is new BookingOptionRequest?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#123]
According to the ontology, Booking and CO2CalcMethod are deprecated classes, but Request is not: 
![image](https://user-images.githubusercontent.com/1225647/118616005-96b5cc80-b7c1-11eb-89a6-8f987b973d28.png)

**Comment by lambertciata** [comment]
Yes it will be fixed with new version, thanks for showing that.
