### ISSUE TITLE
BookingOptionRequest#parties should be a collection of OtherParty

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#124]
Currently a BookingOptionRequest can have only one OtherParty as its "parties", as specified in the ontology. Do you confirm this a mistake?

**Comment by lambertciata** [comment]
It seems it is a mistake indeed, this shall be fixed in next version as the OtherParty will change to Party and things are being simplified.

**Comment by grichka** [comment]
Ok, do you know when the next version is planned to be released?

PS: usually a github issue is closed when the fix has been released ;)

**Comment by lambertciata** [comment]
Hopefully next week the updated ontology should be finalized

**Comment by grichka** [comment]
Thx, Great news!
Will you also publish a changelog, to guide people like me through migrating to the new version?
