### ISSUE TITLE
[API] How to PATCH properties like Item.dimensions.volume.value?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#125]
ONE Record API standard includes specification of PATCH for "ownned" properties, inspired from [json-ld-patch](https://github.com/digibib/ls.ext/wiki/JSON-LD-PATCH).
 
For example, here is the body of a PATCH request aiming to modify the value of Item.lotNumber:

```json
{
  "@type": ["https://onerecord.iata.org/api/PatchRequest"],
  "https://onerecord.iata.org/api/PatchRequest#description": "Change company prefix",
  "https://onerecord.iata.org/api/PatchRequest#logisticsObjectRef": {
    "@type": ["https://onerecord.iata.org/api/LogisticsObjectRef"],
    "https://onerecord.iata.org/api/LogisticsObjectRef#logisticsObjectId": "http://uri/companies/companyId/items/1"
  },
  "https://onerecord.iata.org/api/PatchRequest#operations": [
    {
      "@type": ["https://onerecord.iata.org/api/Operation"],
      "https://onerecord.iata.org/api/Operation#o": {
        "@type": ["https://onerecord.iata.org/api/OperationObject"],
        "https://onerecord.iata.org/api/OperationObject#datatype": "https://www.w3.org/2001/XMLSchema#string",
        "https://onerecord.iata.org/api/OperationObject#value": "1"
      },
      "https://onerecord.iata.org/api/Operation#op": "del",
      "https://onerecord.iata.org/api/Operation#p": "https://onerecord.iata.org/cargo/Item#lotNumber"
    },
    {
      "@type": ["https://onerecord.iata.org/api/Operation"],
      "https://onerecord.iata.org/api/Operation#o": {
        "@type": ["https://onerecord.iata.org/api/OperationObject"],
        "https://onerecord.iata.org/api/OperationObject#datatype": "https://www.w3.org/2001/XMLSchema#string",
        "https://onerecord.iata.org/api/OperationObject#value": "3"
      },
      "https://onerecord.iata.org/api/Operation#op": "add",
      "https://onerecord.iata.org/api/Operation#p": "https://onerecord.iata.org/cargo/Item#lotNumber"
    }
  ],
  "https://onerecord.iata.org/api/PatchRequest#requestorCompanyIdentifier": "http://uri/companies/companyId",
  "https://onerecord.iata.org/api/PatchRequest#revision": "1"
}
```
The IRI `p` identifies the target property of resource identified by the logisticsObjectRef, and it works fine.

Now my Item is:
```json
{
[...]
  "dimensions": {
    "height": {
      "unit": "cm",
      "value": 6
    },
    "length": {
      "unit": "cm",
      "value": 20
    },
    "volume": {
      "unit": "cubic meters",
      "value": 0.0012
    },
    "width": {
      "unit": "cm",
      "value": 10
    }
  },
  "product": {
    [...]
  },
  "unitPrice": {
    "unit": "USD",
    "value": 999.9
  },
  "weight": {
    "unit": "KG",
    "value": 0.3
  },
[...]
}
```

**What would be the PATCH request body to modify the value of the volume of the dimensions of the Item?**

(In this example dimensions is what is called a "blank node" and is considered as an inline structured object like we have in many classes of ONE Record data model)

**Comment by lambertciata** [comment]
To be discussed with API & security group

**Comment by JorreCobelens** [comment]
I would suggest to change "cubic meters" into "cbm"

![image](https://user-images.githubusercontent.com/94984267/143278841-0e1d5850-a979-4970-b240-bde6915e5b9f.png)

**Comment by mskopp** [comment]
AFAIK the units and codes from IATA CargoXML are the ones to be used.+
So the unit code for cubic meters is 'MTQ'

**Comment by grichka** [comment]
Thanks for correcting my dummy example.
However, this has nothing to do with my original question :)

**Comment by aloccid-iata** [comment]
Dear @grichka,

I am writing to inform you that we will be closing the issue. It has remained open for over two years. For detailed information on updating logistics objects, please refer to this link: [Updating Logistics Objects.](https://iata-cargo.github.io/ONE-Record/logistics-objects/#update-a-logistics-object)

Best regards, 
Davide
