### ISSUE TITLE
[Question] How to handle Shipment Mementos?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#127]
![image](https://user-images.githubusercontent.com/1225647/131311648-585d149c-3f31-4d03-8116-3de5e14f5983.png)

As described by the schema above, at every step of the booking process, a Memento of the shipment should be created.

I see two problems here ;

- The Shipment resource could be hosted by a different server from the one hosting the BookingRequest and BookingOptions. Does it mean that the company hosting the Shipment must listen to all events and handle automated creation of mementos? (not specified by the 1R standard) Or should the company responsible for handling the BookingRequest trigger the mementos? (how?)
- The Shipment contains links to Pieces containing links to Products and many other links. If a Memento of a Shipment is created, it will have links to Pieces but not to mementos of these pieces, right? Should mementos of all linked objects be created then? Is this technically feasible?

**Comment by lambertciata** [comment]
To be discussed with API & Security group

**Comment by lambertciata** [comment]
We removed Memento in API 2.0.0, I close the issue
