### ISSUE TITLE
[API] Which version of JSON-LD to use?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#128]
Developers need to choose proper tools/libraries to support JSON-LD serialization and deserialization. However some of these tools only support JSON-LD 1.0 ([jsonld-java](https://github.com/jsonld-java/jsonld-java) for example), others support version 1.1 ([jsonld.js](https://github.com/digitalbazaar/jsonld.js/) for example).

See the differences of version 1.1 compared to 1.0 [here](https://www.w3.org/TR/json-ld/). Version 1.1 introduces interesting features, especially options for the context.

**ONE Record specification should clearly include the expected JSON-LD specification version to use (1.0, 1.1 or latest).** Note: by default, a JSON-LD API is supposed to support the latest specification (1.1) when processing a JSON-LD document: see [processing-mode](https://www.w3.org/TR/json-ld/#dfn-processing-mode).

**Comment by aloccid-iata** [comment]
https://iata-cargo.github.io/ONE-Record/concepts/#linked-data
Dear @grichka,

I am writing to inform you that we will be closing the issue. It has remained open for over two years. For detailed information on JSON-LD, please refer to this link: [JSON-LD in ONE Record](https://iata-cargo.github.io/ONE-Record/concepts/#linked-data)

Best regards, 
Davide
