### ISSUE TITLE
[Data Model/Mapping] Where to put the AWB currency?

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#129]
(This question is from the XFWB-to-1R converter at https://onerecord.riege.com/ and results from uploading the example message https://onerecord.riege.com/888-11111111_XFWB.xml into the converter)

The (X)FWB/AWB has one "AWB Currency" (field <ApplicableOriginCurrencyExchange><SourceCurrencyCode> in CXML).
Is there any field in 1R to store explicitly the currency on the Waybill or is there intentionally no such field but currency must be stored e.g. in Ratings/Ranges#unitBasis ?

Problem with *not* storing one explicit "AWB Currency" for the Waybill: When 1R data needs to be converted down to XFWB or FWB (e.g. because transmission to customs authorities etc) and if there are *different* currencies stored in the different values in 1R then any field for the "AWB Currency" such as in XFWB or FWB cannot be determined uniquely.

**Comment by lambertciata** [comment]
In current proposal, AWB Currency was meant to be on Price/grandTotal/Value/unit. Discussion required to assess if that is enough or if a specific awbCurrency data property is required on the Waybill object.

**Comment by lambertciata** [comment]
Approach chosen is to add a awbCurency (or other name) on the Waybill object. Currency should refer to ISO lists.
