### ISSUE TITLE
pieceDetails definition in piece-grouping.json + piece.json

### ISSUE THREAD

**Issue by larspijnappel** [IATA-Cargo/ONE-Record#13]
Hi Andra,

First of all, thanks for processing the reported issues: it's much appreciated. 

I noticed that the attribute **PieceDetails** is currently used in both the `piece-grouping.json` and `piece.json` and both are referring to the `logistics-component.json`. 
However, the `logistics-component.json` has the attribute **ContainedPiece** which refers back to the `piece.json`. 

So, basically, the "hierarchy" of these attributes works likes this:
`air-waybill.json` > **WaybillLine** > `piece-grouping.json` > **PieceDetails** > _`logistics-component.json`_ > **ContainedPiece** > _`piece.json`_ > **PieceDetails** > _`logistics-component.json`_ > etc.

Maybe I miss the correct understanding but are the definitions and relationship between these json schemas not causing any conflicts or misunderstanding??

**Comment by andrablaj** [comment]
Thank you for your comment! I have added your question on : https://tcfplayground.org/LogisticsComponent. The ONE Record Data Model Working Group take care of the ontology, so they should answer there.

**Comment by andrablaj** [comment]
The issue is not relevant anymore. Please refer to the new data model for further questions.
