### ISSUE TITLE
[Data Model/Mapping] How to store NilInsuranceValueIndicator

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#131]
(This question is from the XFWB-to-1R converter at https://onerecord.riege.com/ and results from uploading the example message https://onerecord.riege.com/888-11111111_XFWB.xml into the converter, warning message 'how to handle NilInsuranceValueIndicator, using Insurance#insuranceAmount with Value#unit="NVD" as workaround')

If Insurance is decared as NIL in XFWB/FWB, is the following correct to 'store' this information in 1R?

      "https://onerecord.iata.org/Shipment#insurance" : {
        "@type" : [ "https://onerecord.iata.org/Insurance" ],
        "https://onerecord.iata.org/Insurance#insuranceAmount" : {
          "@type" : [ "https://onerecord.iata.org/Value" ],
          "https://onerecord.iata.org/Value#unit" : "NVD"
        }

The assignment `"unit" : "NVD"` does not feel to be an obvious natural mapping.

If this is the designated assignment then it should clearly be documented in `Value` and maybe also in `Insurance`,

**Comment by lambertciata** [comment]
My proposal:
- Add a No Value Declared on Insurance to cover the use case
- InsuranceAmount should be 0:1 and nvdIndicator 0:1

**Comment by lambertciata** [comment]
Proposal validated
