### ISSUE TITLE
[Data Model/Mapping] How to store NilCarriageValueIndicator and NilCustomsValueIndicator

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#132]
(This question is from the XFWB-to-1R converter at https://onerecord.riege.com/ and results from uploading the example message https://onerecord.riege.com/888-11111111_XFWB.xml into the converter, warning messages 'how to handle NilCarriageValueIndicator, using Piece#declaredValueForCarriage with "NVD" as workaround' and 'how to handle NilCustomsValueIndicator, using Piece#declaredValueForCustoms with "NVD" as workaround')

If CarriageValueIndicator is decared as NVD in XFWB/FWB and/or
if CustomsValueIndicator is decared as NVD in XFWB/FWB and/or, is the following correct to 'store' this information in 1R?

        "https://onerecord.iata.org/Piece#declaredValueForCarriage" : [ "NVD" ],
        "https://onerecord.iata.org/Piece#declaredValueForCustoms" : [ "NVD" ],

The assignment `"declaredValueForCarriage/Customs" : "NVD"` does not feel to be an obvious natural mapping.

If this is the designated assignment then it should clearly be documented in `Piece` / the Piece fields in the Ontology.

**Comment by lambertciata** [comment]
My proposal:
- Add nvdForCustoms and nvdForCarriage on Piece, both are booleans
- Change cardinality to 0:1 for all fields declaredValueforCustoms, declaredValueForCarriage, nvdForCustoms and nvdForCarriage.

**Comment by lambertciata** [comment]
Proposal validated, add the condition that:
- Either Value or NVD needs to be entered
- If NVD is false, a Value needs to be entered
