### ISSUE TITLE
[Data Model/Mapping] How to store SignatoryCarrierAuthentication

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#133]
(This question is from the XFWB-to-1R converter at https://onerecord.riege.com/ and results from uploading the example message https://onerecord.riege.com/888-11111111_XFWB.xml into the converter, warning message 'which event code to use for SignatoryCarrierAuthentication, using eventCode="SIGNATURE_CARRIER" as workaround').

The XFWB/FWB has data fields for SignatoryCarrierAuthentication (plus one data field for Signatory of Consignor).

We are storing this data in 1R `Event` but the `eventCode` to be used should be documented clearly in the Ontology.

Example:

    "events" : [ {
      "dateTime" : "2021-03-20T00:00:00",
      "@type" : [ "https://onerecord.iata.org/Event" ],
      "https://onerecord.iata.org/Event#location" : {
        "https://onerecord.iata.org/Location#code" : "ORK"
      },
      "https://onerecord.iata.org/Event#performedByPerson" : {
        "https://onerecord.iata.org/Person#lastName" : "Name of the User is here"
      },
      "https://onerecord.iata.org/Event#eventCode" : "SIGNATURE_CARRIER"
    } ],

Since Ontology 1.1 does not document the correct eventCode to be used, we applied `SIGNATURE_CARRIER` here.
For Signatory of Consignor we intend to use `"eventCode" = "SIGNATURE_CONSIGNOR"`.

**Please also note that the Signatory of Consignor in (X)FWB (CIMP Segment 16, "Shipper’sCertification") does provide a timestamp but `dateTime` is mandatory for an event!**

Is this the designated way to store this information? If yes, please clearly document the event codes in the Ontology. If this is not the designated way then please provide the correct way.

**Comment by lambertciata** [comment]
This impacts 4 different fields in XFWB:
- Consignor Declaration Signature, Carrier Declaration Date, Carrier Declaration Place and Carrier Declaration Signature
- Event does not seem to be the best way to handle those, my proposal would be to add additional fields on the Waybill object

**Comment by lambertciata** [comment]
Proposal validated
