### ISSUE TITLE
[Data Model/Mapping] How to store HandlingOSIInstructions and HandlingSSRInstructions

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#134]
(This question is from the XFWB-to-1R converter at https://onerecord.riege.com/ and results from uploading the example message https://onerecord.riege.com/888-11111111_XFWB.xml into the converter, warning message 'where to put HandlingOSIInstructions, using ServiceRequest with code="OSI" as workaround').

The XFWB/FWB has different data fields for OSI (OtherServiceInformation) and SSR (SpecialServiceRequest), XFWB fields are HandlingOSIInstructions and HandlingSSRInstructions
The 1R `ServiceRequest` does not explicitly differentiates between both but has a `code` field.

What is the correct `code` field value for OSI and for SSR? Shall one use `"code" : "OSI"` and `"code" : "SSR"`? See also #135
Is the following correct?

          "https://onerecord.iata.org/ServiceRequest#code" : "OSI",
          "https://onerecord.iata.org/ServiceRequest#statementText" : "HANDLE WITH CARE"

If yes, please clearly document the codes in the Ontology.

**Comment by lambertciata** [comment]
My proposal:
- Use SSR and OSI to refer to those in the ServiceRequest#code field
- Mention in the description the mapping

**Comment by lambertciata** [comment]
For the time being use the ServiceRequest as proposed, in the mean time assess with CMWG usage.

**Comment by mskopp** [comment]
Note: On ServiceRequest in 1R, we currently use the following fields when converting from XFWB
* `code`, which we fill with "OSI" or "SSR" here)
* `statementType`, which we fill from optional XFWB field Handling[OSI/SSR]Instructions/`DescriptionCode`)
* `statemenText`, which we fill from XFWB field Handling[OSI/SSR]Instructions/`Description`)

Example XFWB segment:

> &lt;HandlingOSIInstructions>
> &nbsp;&nbsp;&nbsp;&nbsp;&lt;Description>HANDLE WITH CARE&lt;/Description>
> &lt;/HandlingOSIInstructions>

**Comment by mskopp** [comment]
With Ontology 2.0.0 OSI/SSR text goes to ("OSI" example here):

    {
          "@type" : [ "https://onerecord.iata.org/HandlingInstructions" ],
          "https://onerecord.iata.org/HandlingInstructions#serviceDescription" : "HANDLE WITH CARE",
          "https://onerecord.iata.org/HandlingInstructions#serviceType" : "OSI"
    }

while special handling codes e.g. go to

      {
          "@type" : [ "https://onerecord.iata.org/HandlingInstructions" ],
          "https://onerecord.iata.org/HandlingInstructions#serviceType" : "SPH",
          "https://onerecord.iata.org/HandlingInstructions#serviceTypeCode" : "NSC"
      }

So this issue could be closed from my point of view

**Comment by lambertciata** [comment]
Agree, added to the changelog for reference
