### ISSUE TITLE
[Data Model/Mapping] How to store AssociatedConsignmentCustomsProcedure

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#135]
(This question is from the XFWB-to-1R converter at https://onerecord.riege.com/ and results from uploading the example message https://onerecord.riege.com/888-11111111_XFWB.xml into the converter, warning message 'where to put AssociatedConsignmentCustomsProcedure, using ServiceRequest with code="COR" as workaround').

The XFWB/FWB has an explicit data fields for AssociatedConsignmentCustomsProcedure, which is mandatory to be declared due to legal reasons in some regions.
We are not sure where to put this in 1R, as a workaround we placed it in a 1R `ServiceRequest`. If this is the right way, then please provide the correct `ServiceRequest#code` to be used.
Is the following correct to store <AssociatedConsignmentCustomsProcedure>X</AssociatedConsignmentCustomsProcedure> ? (or in FWB: `COR/X`)

          "https://onerecord.iata.org/ServiceRequest#code" : "COR",
          "https://onerecord.iata.org/ServiceRequest#statementText" : "X"

If yes, please clearly document the codes in the Ontology. See also #134.

In CargoIMP, this is the "COR" segment in FWB and typically covers some EU-customs identifier as "T1" or "T2" or "X" or else.
A "COR" segment in CargoIMP is also found in the messages FAI (Freight Agent Information) and CIR (Customs Inventory Report).

**Comment by lambertciata** [comment]
This should be part of CustomsInfo object that is linked to the Piece. Needs a review to align with XFWB specifications.

**Comment by mskopp** [comment]
Well "CustomsInfo" sounds like a match since the AssociatedConsignmentCustomsProcedure contains kind of "customs information" but CustomsInfo is used to reflect the "OCI" segment as per  https://www.iata.org/contentassets/4bb3450ef9a2447493a132b38fac1d26/oci-composition-rule-table.pdf.
But this value here does not fit in any OCI category and also is a single value which reflects local/legal customs codes if applicable.

**Comment by lambertciata** [comment]
Information is important, there is a need to map this field.

**Comment by mskopp** [comment]
With Ontology 2.0.0 it will go to

      "https://onerecord.iata.org/Waybill#customsOriginCode" : "X",

so this could be closed. Thanks.
