### ISSUE TITLE
[Ontology] Don't use the "&" character in rdfs:comment 

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record#137]
Some Ontology files contain the ampersand character in rdfs:comment.

Problem with this is, when following the instruction from
https://github.com/IATA-Cargo/one-record-server-java/blob/master/README.md
to generate ONE Record related data model,
then it fails because it generates the ampersand character into Java-Class comment lines and Java does not like that when generating API documentation of the generated Java classes.

E.g. this ontology contains 3x the "&" character in rdfs:comment:
https://github.com/IATA-Cargo/ONE-Record/blob/master/working_draft/ontology/IATA-1R-DM-Ontology.ttl

Replacing the "&" with a simple "and" or plus sign will help.

**Comment by lambertciata** [comment]
Thanks for noticing that, updated the ontology and removed the & in the comments.
