### ISSUE TITLE
[Data Model] ServiceRequest lost

### ISSUE THREAD

**Issue by DrPhilippBillion** [IATA-Cargo/ONE-Record#140]
According to Protege, the ServiceRequest as separate object connected with the piece is deprecated. Why and where to put the information?

**Comment by lambertciata** [comment]
Hello, according to release notes (https://github.com/IATA-Cargo/ONE-Record/blob/master/May-2022-standard-forCOTBendorsement/Data-Model/IATA-1R-DM-ReleaseNote-vCOTB-May2022.md) it is replaced with HandlingInstructions.
