### ISSUE TITLE
shipment#waybillNumber should be marked as deprecated

### ISSUE THREAD

**Issue by DrPhilippBillion** [IATA-Cargo/ONE-Record#141]
As the waybillNumber is part of the Waybill LO, the data field in the Shipment should be removed or marked as deprecated

**Comment by mskopp** [comment]
I am not sure, maybe waybillNumber in shipment number is designed to keep the HOUSE waybill number?

**Comment by lambertciata** [comment]
The waybillNumber in Shipment should not be here indeed. It should have been removed with previous versions. I removed in the workingdraft (https://github.com/IATA-Cargo/ONE-Record/commit/b922aedd671cbfbd324f5c33e0ed6f72fc5d618f) and will align with version for endorsement

**Comment by DrPhilippBillion** [comment]
Thx!
