### ISSUE TITLE
[Data Model] Recommended to change the attribute linkedObject of the Event from ObjectProperty to String

### ISSUE THREAD

**Issue by scott-wong** [IATA-Cargo/ONE-Record#142]
Changed the attribute linkedObject of the Event from ObjectProperty to String to facilitate API requests.

`{
...
  "iata-cargo:Event#linkedObject": "http://localhost:8080/companies/iata/los/Piece_017876",
...
}`

**Comment by lambertciata** [comment]
Hi,
Actually, linkedObject property uses the URIs of the LOs so it is basically the same as strings except no "" should be necessary.

**Comment by scott-wong** [comment]
Got it, thank you.
