### ISSUE TITLE
[Ontology] Recommended units for https://onerecord.iata.org/cargo/Value#unit

### ISSUE THREAD

**Issue by ddoeppner** [IATA-Cargo/ONE-Record#151]
When converting data from different source systems into the ONE Record data standard, it is often the case that units of measurement and currencies have to be converted. Accordingly, codes or units must be defined for the Value#unit property.

It might be helpful to agree on and recommend a list of codes that should be used for the Value#unit property, or provide references to preferred code collections, such as the GS1 US Unit of Measure list or ISO (currency) codes that should be used.

See [GS1 US Unit of Measure Codes](https://resources.gs1us.org/GS1-US-Data-Hub-Help-Center/ArtMID/3451/ArticleID/116/Unit-of-Measure-Codes)

See [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)

**Comment by lambertciata** [comment]
Hi,

Interesting point, I guess it all depends on which standard we can rely on. To be discussed by the task force.

**Comment by mskopp** [comment]
AFAIK this has been discussed with task force already and outcome was that the units/unit-codes used in CargoXML should be used in 1R as well.

**Comment by lambertciata** [comment]
Cleared with 3.0.0
