### ISSUE TITLE
Loop - BookingOptionRequest - BookingSegment - BookingOptionRequest

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#153]
Currently we have a loop:
We have BookingOptionRequest - BookingSegment - BookingOptionRequest again.
In my option we should delete BookingOptionRequest (iata:bookingSegment:requests) from BookingSegment.

{
   "@context": {
      "iata": "https://onerecord.iata.org/"
   },
   "@type": "iata:BookingSegment",
   "iata:bookingSegment:arrivalLocation" : {
      "@id": "iata:Location/thisObjectId",
      "@type": "iata:Location"
   },
   "iata:bookingSegment:bookingOptions" : {
      "@id": "iata:BookingOption/thisObjectId",
      "@type": "iata:BookingOption"
   },
   "iata:bookingSegment:departureLocation" : {
      "@id": "iata:Location/thisObjectId",
      "@type": "iata:Location"
   **},
   "iata:bookingSegment:requests" : {
      "@id": "iata:BookingOptionRequest/thisObjectId",
      "@type": "iata:BookingOptionRequest"**
   },
   "iata:bookingSegment:preferredTransportId" : "string"
}

**Comment by lambertciata** [comment]
Hi again, 

I answered also on #154 , this case can be discussed indeed for the BookingSegment.

**Comment by lambertciata** [comment]
Cleared, it's part of linked data principle
