### ISSUE TITLE
[Ontology] link from BookingOptionRequest to BookingOption is missing

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#155]
link from BookingOptionRequest to BookingOption is missing
currently there is no option to link a waybillNumber to bookingOptionRequest;
wayBill is part of BookingOption, which should be connected to BookingOptionRequest

**Comment by lambertciata** [comment]
Hi, indeed the link from BookingOptionRequest to BookingOption is missing, will add that thanks!

**Comment by lambertciata** [comment]
Cleared with 3.0.0
