### ISSUE TITLE
[json-ld] contactOther is just a type

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#156]
contactOther is just a type
there are no fields / no content 

{
   "@context": {
      "iata": "https://onerecord.iata.org/"
   },
   "@type": "iata:ContactOther"
}

**Comment by ddoeppner** [comment]
The class ContactOther (IRI=https://onerecord.iata.org/ContactOther) should not be used any longer as it is already marked as deprecated. see
https://github.com/IATA-Cargo/ONE-Record/blob/master/working_draft/ontology/IATA-1R-DM-Ontology.ttl#L677


```
###  https://onerecord.iata.org/Contact#other
contact:other rdf:type owl:ObjectProperty ;
              rdfs:domain :Contact ;
              rdfs:range :ContactOther ;
              rdfs:comment "Other contact options e.g. Skype, Whatsapp, Viber, Fax etc"@en ;
              rdfs:label "contact:other"@en ;
              owl:deprecated "true"@en .
```
