### ISSUE TITLE
[Ontology] changeRequest: link from shipment to ULD

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#160]
In Lufthansa we have ULD information for the whole shipment.
Is it possible to get a link from shipment directly to ULD?
In the current onotology you have to go through piece.

**Comment by gxclark** [comment]
Is it not commonplace for pieces of the same shipment to be loaded onto different ULDs?  As a result, there is a natural many-to-many relationship between shipment and ULD, implemented as piece.  Are you asking for an optimization within the model so data access is easier and faster, but only in the case when the complete shipment fits into a single ULD?  Or perhaps an array of shipment URIs on a ULD?

**Comment by DrPhilippBillion** [comment]
Dear Laura, Geoff, the approach here follows the principle of the digital twin. In this case: the piece is physically loaded into a ULD, the ULD is then loaded on an aircraft, etc. and pieces belong to a shipment. Thus there can be a many-to-many relation between shipment and ULD. If we create a direct link ("shortcut"), it makes some people´s lifes easier, but will also result in a wast source of confusion and redundancy. Thus I´d prefer to keep this physical-orientation and work with inheritance here (Shipment => piece => ULD). @LauraWeissgerber @gxclark
