### ISSUE TITLE
[Ontology] changeRequest: new fields in ULD: contourCode, dryIce, dryIceWeight (value)

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#161]
We are missing the ULD information for:
- contourCode (string)
- dryIce (boolean)
- dryIceWeight (link to vlaue)

Is it possible to integrate these fields in "ULD"?

**Comment by lambertciata** [comment]
Hi,

The contour code is already contained in the TypeCode, it is the last of the 3 letters.

For dryIce and dryIceWeight we can have it proposed to the taskforce for evaluation.
