### ISSUE TITLE
[Ontology] changeRequest: new fields in BookingOptionRequest: expectedSpeed, expectedCarrierProductCode

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#162]
We are missing the option / the fields in BookingOptionRequest to name
- expectedSpeed (string)
- expectedCarrierProductCode (string)
Is it possible to integrate these fields in BookingOptionRequest?

**Comment by lambertciata** [comment]
Hi Laura,

- expectedSpeed: as of now as there is no standardization of how speed is expressed (e.g. "Standard" is different for each carrier), my proposal would be to use the BookingShipment object (to be created as part of next release) and one of its data property (I believe using the existing HandlingInstructions object would make the most sense)
- expectedCarrierProductCode: This one should already exist so it is missing and will be added

**Comment by LauraWeissgerber** [comment]
Hi Christophe,

thanks for your reply.
Right now we have handlingInstructions just for pieces, not for the whole shipment. So this is planned in the next release to connect handlingInstructions for shipment? 

Do you mean it like this?
BookingOptionRequest - Shipment - handlingInstructions - serviceType: "speed"
BookingOptionRequest - Shipment - handlingInstructions - serviceDescription: "td.Flash"

But right now we just have a range for "serviceType" of this: { "OSI" , "SPH" , "SSR" }
Then we would need a new serviceType "speed" or something like that.

Regarding the carrierProductCode.
Right now we have BookingOptionRequest - BookingOption - carrierProductInfo.
In my option carrierProductCode should also be possible to be requested by the consumer/customer directly in the request. That's why we thought abount "expectedProductCode" in BookingOptionRequest. Alternative we could link "CarrierProduct" as "expectedCarrierProduct" in the BookingOptionRequest (BookingOptionRequest - expectedCarrierProduct - CarrierProduct).
What do you think?
In the response it makes sense that the productCode is part of BookingOption.

**Comment by lambertciata** [comment]
Cleared with 3.0.0
