### ISSUE TITLE
[Ontology] changeRequest: new field "quotationId" in BookingOptionRequest

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#163]
We are missing the field "quotationId" or "quoteId" (string) in BookingOptionRequest.
Please add the field "quotationId" (string) in BookingOptionRequest.

Customers have the option to see their special rates if they send us their quoteId. Therefore we have currently no option in the specification to enter this.

**Comment by lambertciata** [comment]
Can you be more specific as to what quotation id is? Is it a customer id?
I will address the topic to the taskforce as there are 2 possibilities:

1. Using current model, the ID can be defined via the Parties-Company-Branch-OtherIdentifier. 
2. Adding a dedicated field in the BookingOptionRequest

**Comment by LauraWeissgerber** [comment]
Quotation is a "special price" for a customer / consumer; quotation ID is an identifier to see this special rate.
In my option it is not part of parties or companies. It belongs to the booking option request or to rating preferences.

So it is not a customer id.

**Comment by lambertciata** [comment]
Thanks it's clear now, this point along with issue #165 makes me wonder if we should have a specific RatingsPreference object only the for request that would contain data such as specific identifier, promocode, etc.
To be discussed with taskforce

**Comment by lambertciata** [comment]
closed with 3.0.0
