### ISSUE TITLE
[Ontology] changeRequest: new field "nonStopFlight" (boolean) in "routing"

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#164]
Is it possible to add a new field "nonStopFlight" (boolean) in "routing"?
Customers should have the option to enter if they just want to see nonStopFlights.

Question to the current specification:
What is meant by "maxConnections"? If I enter there 0, do I just get nonStopFlights?
If yes, then we do not need a new field "nonStopFlight".

**Comment by ddoeppner** [comment]
I propose to define that maxConnections=1 means nonStopFlight.

Example: Consider a logistics network with nodes and edges.

> maxConnections = 1 would be the connection between one node (airport A) and a second node (e.g. airport B).
> maxConnections = 2 would allow a transit flight from A->B->C, where -> is the connection, right?

Accordingly, maxConnections should be a value greater than or equal to 1 if the property is required and set?

**Comment by mskopp** [comment]
So "0" means direct flight and "1" means direct flight as well since it is "1 connection"?

why not use a property "maxStopps" (or more precise: "maxFlightChanges") where 0 means direct flight and 1 means one stopp = 2 flights.

Various PAX flight search portals (e.g. https://www.google.com/travel/flights) use the same terminology with "Stops" referring to number of a flight change locations.

**Comment by lambertciata** [comment]
I think it's more common to use 0 for direct flight since we are talking about connections (or stops or transits). To be honest I see nothing wrong with maxConnections as of today.

**Comment by DrPhilippBillion** [comment]
Let´s discuss this in the group before closing, please

**Comment by LauraWeissgerber** [comment]
@DrPhilippBillion I reopened the ticket

**Comment by gxclark** [comment]
Freight and PAX are different ... passengers care if the plane stops, even if it is just for fuel and no one alights or boards the plane.  Freight, while it might be time-sensitive, as long as it arrives on-time, it is fine.  That said, direct vs circuitous routing matters for both.  The industry consensus definition of connection is more generic than flights.  If I'm going to fly to catch a scheduled truck route that is planned to haul the shipment to the consignee, that is a connection, even if the flight was direct/non-stop.  As evidence, take the UNECE Supply Chain Reference Data Model, (UNECE_DocumentNameCode_D21B.xsd) ...

      <xsd:enumeration value="489">
        <xsd:annotation>
          <xsd:documentation xml:lang="en">
            <ccts:Name>Reefer connection order</ccts:Name>
            <ccts:Description>Order to connect a reefer container to a reefer point.</ccts:Description>
          </xsd:documentation>
        </xsd:annotation>

This is in the context of a cool chain, where gaps in temperature control through the connection are essential to keep the cool chain intact.¥ and effective.

For this reason, to avoid ambiguity, I recoomend "maxFlights" vs "maxConnections", but they key is in the definition.
