### ISSUE TITLE
[Ontology] changeRequest: phoneNumber & eMail for person

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#169]
Currently I am not sure where to put phoneNumber and eMail for a person.
As a workaround I can use otherIdentifier in companyBranch:
BookingOptionRequest - shipment - company - companyBranch -  otherIdentifierer

Example / Use case:
For temperature sensitive goods we need contact information (phone, email).
In my opinion these information would belong to "person".

Option 1: Link from "person" to "otherIdentifier"
BookingOptionRequest - shipment - company - companyBranch - person - otherIdentifierer
otherIdentifierType: eMail
identifier: max.mustermann@email.com

Option 2: Add new fields "eMail" & "phone" to "person"

What do you think about this?
How could you in the current specification set eMail and phone of a person (example: contact for temperature sensitive goods)?

**Comment by mskopp** [comment]
AFAIK phone, fax, email is handled via Person#contact array and contactType.

E.g.

            {
            "@type" : [ "https://onerecord.iata.org/Person" ],
            "https://onerecord.iata.org/Person#contact" : [ {
              "@type" : [ "https://onerecord.iata.org/Contact" ],
              "https://onerecord.iata.org/Contact#contactType" : "Phone number",
              "https://onerecord.iata.org/Contact#contactValue" : "353123456789"
            }

See also https://onerecord.riege.com which also contains a demo XFWB with a phone number.

**Comment by LauraWeissgerber** [comment]
In the ontology "contactType" has range { "Customer contact" , "Customs contact" , "Emergency contact" , "Other" }.
https://onerecord.iata.org/cargo#Person#contactType

So I thought "phone numver" is not possible.
So we should extend the range of "contactType" with "phone" and "eMail"?

**Comment by mskopp** [comment]
<img width="1049" alt="Contact#contactType" src="https://user-images.githubusercontent.com/8545554/195330201-6e693b44-0738-4e2f-9be4-cb2299ea15ba.PNG">

**Comment by lambertciata** [comment]
Hi,
In fact there is Person#contactType which is supposed to be within { "Customer contact" , "Customs contact" , "Emergency contact" , "Other" } range
And there is Contact#contactType which is supposed to be within the range displayed above.

To avoid misunderstanding the Person#contactType could be renamed.

**Comment by LauraWeissgerber** [comment]
Sorry, now I got it. It's okay like that :)
