### ISSUE TITLE
[Ontology] changeRequest: "statusRemark" in BookingOption

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#173]
I miss the option to fill remarks in BookingOptions, e.g. if an automatic confirmation is not possible (will be queued due to e.g. capacity reasons).

Proposal:
New field "statusRemark" or "statusDescription" or "remark" (string) in BookingOption.

**Comment by lambertciata** [comment]
I think it's a point we have highlighted with MC working group but have not quite figured out what would be the best way to communicate such information. (part of the API response, part of the objects with a dedicated data property, etc.)

**Comment by lambertciata** [comment]
Cleared with 3.0.0
