### ISSUE TITLE
[Ontology] changeRequest: rename "aircraftPossibilityCode" in "aircraftType" OR "aircraftCode"

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#174]
Can we rename "aircraftPossibilityCode" in "aircraftType" OR "aircraftCode"? 

"possibility" makes the name unnecessary long and I think everybody knows that there might be the risk that the aircraft type can change...

**Comment by lambertciata** [comment]
Hi, the aircraft possiblity code refer to a specific Code List in the CXML toolkit: 1.46 which has values such as 

> Mixed configuration (Combi) aircraft carrying Loose Load Cargo on the passenger deck - BBQ

> Pure freighter flight carrying Loose Load Cargo - BBF

In fact the reference to this code list is missing in the ontology, I will change the description.

**Comment by lambertciata** [comment]
Cleared with 3.0.0 in CodeList ontology
