### ISSUE TITLE
[Ontology] changeRequest: "remark" in BookingOption or Routing

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#175]
I miss the option to fill (station) remarks, e.g. for certain stations or countries is an embargo for alcohol on trucks.
Can we add a "remark" field in BookingOption or in "scheduledLegs" (in case the remark is only for a transit station)?
I think I would prefer "remark" in BookingOption.

What do you think or where would you see these kind of information?

**Comment by lambertciata** [comment]
Hi,
So far our goal has been to avoid free text as much as possible to have standardized data properties. I suggest to discuss that with the taskforce to get more feedback.

Will update the issue accordingly.

**Comment by LauraWeissgerber** [comment]
Instead of "remark" we can name the field "restrictions", so it won't be a normal free text field.
We can also add a link to location, so we show for which locationCode the restricition applies.

**Comment by lambertciata** [comment]
Closed with 3.0.0
