### ISSUE TITLE
[Ontology] changeRequest "allotment" in BookingOption - Price - Rating / where to add "allotment" in BookingOption Ratings?

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#176]
In the current specification there is just in BookingOptionRequest the reference option to an alloment.

In case we offer allotments in the BookingOption, there is currently no field for this.
So the customer does not know that we offer allotment rates in our BookingOption.
Can we add "allotment" in BookingOption - Price - Rating?
Or where would you add this information?

OR: Is this meant by "priceSpecification" or "priceSpecificationRef" that we would here add the allotment name?

**Comment by lambertciata** [comment]
Hi, this needs double check but I think that:
- priceSpecification should mention "Allotment"
- priceSpecificationRef should mention the allotment reference itself if necessary
