### ISSUE TITLE
[Ontology] address.addressCode and addressCodeType are n-ary

### ISSUE THREAD

**Issue by Waitak** [IATA-Cargo/ONE-Record#177]
Neither the addressCode and addressCodeType fields in the Address class has maxCardinality set to 1 in the May '22 ontology. In the data model, addressCodeType has maxCardinality of 1, but addressCode is n-ary. My guess would be that this is an oversight and both should have maxCardinality of 1.

**Comment by lambertciata** [comment]
Hi, I tend to agree, we'll discuss it with the taskforce. Thanks
