### ISSUE TITLE
[DM ontology 2.1.0] Descriptions of classes "Value" and "VolumetricWeight" are mismatched

### ISSUE THREAD

**Issue by NiclasScheiber** [IATA-Cargo/ONE-Record#183]
As of datamodel version 2.1, comment (annotation) of class "Value" is "Volumetric weight details" and comment (annotation) of class "VolumetricWeight" is "Unit of measurement details" which I believe should be the other way around

**Comment by lambertciata** [comment]
Added to https://github.com/IATA-Cargo/ONE-Record/commit/5515ccf3fabee8ca9845c065035f8aa53f9b11fb
