### ISSUE TITLE
[DM ontology 2.1.0]: Prefix for class "Adjustments" is missing

### ISSUE THREAD

**Issue by NiclasScheiber** [IATA-Cargo/ONE-Record#184]
The TTL has no prefix for the newly added class "Adjustments", there should be a
`@prefix measurements: <https://onerecord.iata.org/Adjustments#> .`

**Comment by lambertciata** [comment]
Added to https://github.com/IATA-Cargo/ONE-Record/commit/5515ccf3fabee8ca9845c065035f8aa53f9b11fb
