### ISSUE TITLE
[DM ontology 2.1.0]: Datafield "taxDueAirlines" should be restricted to only, not some "Value" objects

### ISSUE THREAD

**Issue by NiclasScheiber** [IATA-Cargo/ONE-Record#185]
Object property "taxDueAirline" in class "BillingDetails" should be restricted to only (universal) "Value" objects, not some (existential) to be consistent with other properties in the DM - even if it makes no difference due to the cardinality restriction.

**Comment by lambertciata** [comment]
Added to https://github.com/IATA-Cargo/ONE-Record/commit/5515ccf3fabee8ca9845c065035f8aa53f9b11fb
