### ISSUE TITLE
piece_grouping_totals.json in house_waybill.json

### ISSUE THREAD

**Issue by YewKong** [IATA-Cargo/ONE-Record#19]
In house-waybill.json schema, there is segment that reference to 'piece_grouping_totals.json'.  Should this segment also be removed in house_waybill.json?
 
"HouseWaybillLineTotals": {
         "description": "House waybill line totals",
         "required": true,
         "type": "piece_grouping_totals.json"
      },

**Comment by andrablaj** [comment]
The update was made in: https://github.com/IATA-Cargo/ONE-Record/pull/20
