### ISSUE TITLE
Ontology: empty prefix and xsd prefix are missing

### ISSUE THREAD

**Issue by thmoreau** [IATA-Cargo/ONE-Record#2]
Great rework already!
I tried to parse the ontology and use it with [Apache Jena](https://jena.apache.org/).
I faced 2 minor issues:
- the empty prefix is missing. I assumed it was like: `@prefix : <http://cargo.iata.org#>`
  also I removed `iata` prefix.
- the xsd prefix is missing: I added `@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .`

**Comment by andrablaj** [comment]
Thank you for your comments! I have just tried to parse the `.ttl` with Jena, and I got the same issues. I have corrected the problem in https://github.com/IATA-Cargo/ONE-Record/pull/16.
