### ISSUE TITLE
API spec authentication & authorization page lists wrong endpoints for action requests

### ISSUE THREAD

**Issue by domkun** [IATA-Cargo/ONE-Record#201]
The summary table of endpoints in the API Specs on the "Authentication & Authorization" page has wrong endpoints for action requests listed. The endpoints in the table are named `access-requests`, but should be `action-requests`.

See https://github.com/IATA-Cargo/ONE-Record/blob/eddd36fc6960e7a3b4838e1caa8ce6a12383ff38/working_draft/API/docs/security/authn-application-layer.md?plain=1#L429-L431

**Comment by IATA-Cargo** [comment]
Thanks Dominik. I am going to fix it right now

**Comment by IATA-Cargo** [comment]
Fix with commit https://github.com/IATA-Cargo/ONE-Record/commit/6e03d3346cc7b9e4983b978b7007aaf7065054d0
