### ISSUE TITLE
waybillNumber [ xsd:pattern "[-9]+" incorrect, could be "[-0-9]+"

### ISSUE THREAD

**Issue by chewjin** [IATA-Cargo/ONE-Record#213]
###  https://onerecord.iata.org/ns/cargo#waybillNumber
:waybillNumber rdf:type owl:DatatypeProperty ;
               rdfs:domain owl:Thing ;
               rdfs:range [ rdf:type rdfs:Datatype ;
                            owl:onDatatype xsd:string ;
                            owl:withRestrictions ( [ xsd:pattern "[-9]+"
                                                   ]
                                                 )
                          ] ;
               rdfs:comment "House or Master Waybill unique identifier"@en ;
               rdfs:label "waybillNumber"@en .

**Comment by NiclasScheiber** [comment]
You are correct, although I suggest to remove the pattern altogether since House Waybills may use alphanumeric characters or change to:

[A-Z0-9]+
