### ISSUE TITLE
the maxCardinality of vehicleModel should not be nonNegativeInteger.

### ISSUE THREAD

**Issue by ShawnLiou-iii** [IATA-Cargo/ONE-Record#216]
https://github.com/IATA-Cargo/ONE-Record/blob/02d47e03f2a63c96b812a528f49299150e96318a/2023-12-standard/Data-Model/IATA-1R-DM-Ontology.ttl#L8695C55-L8695C55

vehicleType is a string. Why is its maxCardinality "nonNegativeInteger"?

**Comment by NiclasScheiber** [comment]
In OWL, max cardinality constraints just mean that the property cannot be present more than the indicated time. Hence it must be a non-negative integer.

The value of the property is not affected by this.

In this example, a **TransportMeans** may have 0 or 1 properties of type **vehicleType** (maxCardinality constraint) and that, if present, a **vehicleType** must hold an embedded object of type CodeListElement (allValuesFrom constraint).

The CodeListElement in turn can hold a code property (eg. "74F"), a description ("747 all Freighter models") and a codeListName ("IATA Aircraft Type Codes").
