### ISSUE TITLE
AccountInformationCode and AccountInformationDescription

### ISSUE THREAD

**Issue by YewKong** [IATA-Cargo/ONE-Record#30]
In the air-waybill.json schema, assuming the elements **AccountInformationCode** and **AccountInformationDescription** are mapped to CIMP **AccountingInformationIdentifier** and **AccountingInformation** respectively; CIMP allows up to six occurrences of these while the schema doesn't.  Should the schema be revised?

**Comment by andrablaj** [comment]
Hi @YewKong and thank you for the feedback, it is a very valid point. Can you please make a change proposal on https://tcfplayground.org/AirWaybill? All the proposals are taken into account by the ONE Record Data Model Working Group?

**Comment by YewKong** [comment]
Thanks @andrablaj, I've updated on the site mentioned.
