### ISSUE TITLE
Piece or item and reference between them

### ISSUE THREAD

**Issue by stevenfayers** [IATA-Cargo/ONE-Record#34]
A logistics_component can contain ContainedItem and ContainedPiece where the Piece basically has the UPID and the Item has serial numbers, production numbers etc. However there is no way to associate a specific UPID (piece) with a specific item to know which UPID is which serial or production number.

**Comment by andrablaj** [comment]
Hi @stevenfayers and thank you for the feedback, it is a very valid point. Can you please make a change proposal on https://tcfplayground.org/LogisticsComponent? All the proposals are taken into account by the ONE Record Data Model Working Group?

**Comment by andrablaj** [comment]
The issue is not relevant anymore. Please refer to the new data model for further questions.
