### ISSUE TITLE
Binary choices not using boolean datatype and defined in negative form

### ISSUE THREAD

**Issue by stevenfayers** [IATA-Cargo/ONE-Record#35]
There are elements which appear to be binary in choice yet are defined with datatype text. There are some that are also defined in negative form where a double negative would need to be coded to make it positive.
For example NoDimensionAvailable under logistics-component is defined as type text.
It would be clearer, more readable and easier to develop if it was defined as:
     "DimensionAvailable": {
         "description": "Dimensions are available for this logistics component",
         "type": "boolean"
      }

Other examples (non-exhaustive):
piece - FlagPieceLevelTracking should be type boolean and should be renamed to remove the word flag and make it more precise - perhaps PieceLevelTrackingRequired 
airwaybill - NoCarriageValue should be "CarriageValueDeclared" datatype boolean

**Comment by andrablaj** [comment]
Closing the issue as boolean fields were created
