### ISSUE TITLE
Common Commodity schema

### ISSUE THREAD

**Issue by RabboniRabi** [IATA-Cargo/ONE-Record#39]
The Commodity name value pair used in logistics-component.json and product.json schemas are the same. Different keys (Issuer and type) are however given within Commodity. The description and type of these two keys are the same.

**Comment by andrablaj** [comment]
Hi @RabboniRabi and thank you for the feedback, it is a very valid point. Can you please make a change proposal on https://tcfplayground.org/LogisticsComponent? All the proposals are taken into account by the ONE Record Data Model Working Group

**Comment by RabboniRabi** [comment]
Hi @andrablaj. This is regarding a question on another topic in one record, but I did not want to create an issue.

In the One Record API specification draft 2, a sample server information response is given:

{
  "@context": {
    "@vocab" : "https://tcfplayground.org/ "
  },
  "@id": "https://myonerecordserver.org/my_license_plate",
  "@type": "ServerInformation",
  "company": {
     "@type": "Company",
     "name": "text",
     "IATACargoAgentCode": "numeric",
     "branch": [{
        "branchName": "text",
        "IATACargoAgentLocationIdentifier": "numeric",
        "otherIdentifier": [{
           "identifierName": "text",
           "identifer": "text"
        }],
        "location": {
           "@type": "Location",
           "type": "text",
           "code": "text",
           "name": "text",
           "geoLocation": {
             "@type": "GeoLocation",
             "latitude": {
               "@type": "Value",
               "value": "text",
               "unit": "text"
             },
             "longitude": {
               "@type": "Value",
               "value": "text",
               "unit": "text"
             },
             "elevation": {
               "@type": "Value",
               "value": "text",
               "unit": "text"
             }
           },
           "address": {
             "@type": "Address",
             "street": "text",
             "POBox": "text",
             "postalCode": "text",
             "cityCode": "text",
             "cityName": "text",
             "regionCode": "text",
             "regionName": "text",
             "countryCode": "text",
             "countryName": "text",
             "addressCodeType": "text",
             "addressCode": "text"
           }
        },
        "contactPerson": {
           "@type": "Person",
           "contactType": "text",
           "salutation": "text",
           "firstName": "text",
           "middleName": "text",
           "lastName": "text",
           "jobTitle": "text",
           "department": "text",
           "employeeID": "text",
           "contactDetails": [{
              "phoneNumber": "text",
              "emailAddress": "text",
              "other": {
                 "type": "text",
                 "detail": "text"
              }
           }]
        }
     }],
     "airlineCode": "text",
     "airlinePrefix": "text"
   },
  "supportedLogisticsObjects": [
"https://tcfplayground.org/HouseManifest", 
"https://tcfplayground.org/Airwaybill"
],
  "supportedContentTypes": [
"application/ld+json", 
"application/x-turtle", 
"text/turtle"],
  "serverEndpoint": "https://myonerecordserver.org/"
}
{
  "@context": {
    "@vocab" : "https://tcfplayground.org/ "
  },
  "@id": "https://myonerecordserver.org/my_license_plate",
  "@type": "ServerInformation",
  "company": {
     "@type": "Company",
     "name": "text",
     "IATACargoAgentCode": "numeric",
     "branch": [{
        "branchName": "text",
        "IATACargoAgentLocationIdentifier": "numeric",
        "otherIdentifier": [{
           "identifierName": "text",
           "identifer": "text"
        }],
        "location": {
           "@type": "Location",
           "type": "text",
           "code": "text",
           "name": "text",
           "geoLocation": {
             "@type": "GeoLocation",
             "latitude": {
               "@type": "Value",
               "value": "text",
               "unit": "text"
             },
             "longitude": {
               "@type": "Value",
               "value": "text",
               "unit": "text"
             },
             "elevation": {
               "@type": "Value",
               "value": "text",
               "unit": "text"
             }
           },
           "address": {
             "@type": "Address",
             "street": "text",
             "POBox": "text",
             "postalCode": "text",
             "cityCode": "text",
             "cityName": "text",
             "regionCode": "text",
             "regionName": "text",
             "countryCode": "text",
             "countryName": "text",
             "addressCodeType": "text",
             "addressCode": "text"
           }
        },
        "contactPerson": {
           "@type": "Person",
           "contactType": "text",
           "salutation": "text",
           "firstName": "text",
           "middleName": "text",
           "lastName": "text",
           "jobTitle": "text",
           "department": "text",
           "employeeID": "text",
           "contactDetails": [{
              "phoneNumber": "text",
              "emailAddress": "text",
              "other": {
                 "type": "text",
                 "detail": "text"
              }
           }]
        }
     }],
     "airlineCode": "text",
     "airlinePrefix": "text"
   },
  "supportedLogisticsObjects": [
"https://tcfplayground.org/HouseManifest", 
"https://tcfplayground.org/Airwaybill"
],
  "supportedContentTypes": [
"application/ld+json", 
"application/x-turtle", 
"text/turtle"],
  "serverEndpoint": "https://myonerecordserver.org/"
}

Shouldnt there a corresponding ServerInformation schema? Or am i missing something?

**Comment by andrablaj** [comment]
Hi @RabboniRabi ! You can find the `serverInformation `model [here](https://github.com/IATA-Cargo/ONE-Record/tree/master/working_draft/API/models).

**Comment by RabboniRabi** [comment]
oops! Thank you!
