### ISSUE TITLE
Ontology vs sample JSON

### ISSUE THREAD

**Issue by stevenfayers** [IATA-Cargo/ONE-Record#42]
In the logistics-component.json there is a section for containedItems and containedPieces:
      "ContainedItem": {
         "description": "Details of contained item(s) ",
         "type": "item.json"
      },
      "ContainedPiece": {
         "description": "Details of contained piece(s)",
         "type": "piece.json"

of type item.json and piece.json respectively.

However the ontology for logisticsComponent (https://tcfplayground.org/LogisticsComponent) says the expected type for both is logisticsComponent (I.e. Recursive children).

**Comment by andrablaj** [comment]
@stevenfayers We have deleted the sample JSON as they were too old and not in compliance with the data model. The logistics component object does not exist anymore in the new data model.
