### ISSUE TITLE
Version Control of API in ONE Record

### ISSUE THREAD

**Issue by LHDrBillion** [IATA-Cargo/ONE-Record#55]
Dear Community,

quick question: Some APIs see it as standard to put the API version in the URI, which could be here: www.onerecordserver.com/forwarderA/v1.2/..... or  www.onerecordserver.com/v1.2/forwarderA/, depending on the setup. It should surely not be on LO level. 

But this is only one option, what is the ONE Record approach on version control of the API here?

Thanks a lot!!

Kind greetings,

Philipp

**Comment by andrablaj** [comment]
The topic was discussed in the ONE Record API & Security Working Group and a proposal was made
