### ISSUE TITLE
Working Draft folder doesn´t contain latest version of working docs

### ISSUE THREAD

**Issue by LHDrBillion** [IATA-Cargo/ONE-Record#8]
Only the API-description is located in the folder "working drafts". The following docs are missing:

- data-model
- ontology
- json schema

Please add so work on it can start

**Comment by andrablaj** [comment]
Thank you for raising this point, Philip. As Github is a versioning framework, we have decided to not duplicate the files and keep a single folder on which we are going to apply new changes. We can retrieve all the files history from Github if we need it.
