### ISSUE TITLE
No SecurityStatus type

### ISSUE THREAD

**Issue by armmarov86** [IATA-Cargo/ONE-Record#81]
In "Piece" datasets, whjere does the SecurityStatus come from ?

securityStatus: SecurityStatus

**Comment by andrablaj** [comment]
@lambertciata can you please advise on this issue? Thanks

**Comment by lambertciata** [comment]
Hi @armmarov86 the securityStatus is a SecurityDeclaration object. The type is right on the detailed xlsx data model but this is a mistake on the pdf version.
Thanks for finding that out.

**Comment by armmarov86** [comment]
I see. Okay thanks for the clarification
