### ISSUE TITLE
[Data Model] Piece.containedPiece should be renamed to Piece.containedPieces

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#83]
A Piece can contain other Pieces in some cases. 
Currently this set of contained Pieces is specified as the property "containedPiece" of a Piece. The plural should be used and this property should be "containedPieces"

**Comment by grichka** [comment]
Actually I think that any list of elements should be plural, and many lists of elements in the model are not :
event, externalReference, upid, transportmeansOperator, transportSegment, otherIdentifier, etc.

But we also have some plural like : transportedUlds, cO2Emissions, transportedPieces, etc.

**Comment by lambertciata** [comment]
Hi,
Thanks for those comments, the plural form for arrays is a valid point, we'll bring that topic up.
Regarding inconsistencies in namings, what version/file are you referring to? Because I don't see any mistake (`upid` on a ULD is a set of pieces for instance)

**Comment by grichka** [comment]
Thanks Christophe!
I'll update my model with the next version as soon as it is available. I can stick with these namings for now.

Regarding inconsistencies I am browsing the [logical Data model](https://github.com/IATA-Cargo/ONE-Record/blob/master/November-2020-standard-COTB-endorsed/Data-Model/IATA-1R-DM-Logical-Data-Model-vCOTB-Nov2020.pdf). 
I just wanted to highlight the fact that a list of Pieces is not called the same in different classes of the model: 
- `upid` of a ULD means that the property is likely to be a string that is the ID of a Piece. However it is a liste of Piece LOs.
- the same kind of list of Pieces is called `transportedPieces` in the TransportSegment
- the same kind of list of Pieces is called `containedPiece` in the Piece
- the same kind of list of Pieces is called `containedPieces`in the Shipment

--> Why not just name it `pieces` when this list has nothing in particular?

Also the naming for a Piece has inconsistencies:
- a Piece is called `piece` in the Security Declaration
- but a Piece is called `isInPiece` in the Item

--> Same here, why not just name it `piece`?

**Comment by andrablaj** [comment]
@lambertciata please close the issues once you solve them in the new Data Model version. Thanks!

**Comment by lambertciata** [comment]
Hi,

Feedback from the data model taskforce:

- All properties that refer to arrays will be renamed to their plural form
- We prefer keeping naming like that (e.g. `piece` and `isinpiece`) in properties names as it contains the context as well and what matters is the type

**Comment by lambertciata** [comment]
This has been done on latest ontology: [Here](https://github.com/IATA-Cargo/ONE-Record/blob/master/June-2021-standard-COTB-endorsed/Data-Model/IATA-1R-DM-Ontology-vCOTB-Jun2021.ttl)
