### ISSUE TITLE
[Data Model] Relationship between Piece and Shipment

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#84]
Hello,
I am currently implementing the ONE Record Data Model and asking myself questions about its content.

For instance, I see that the relationship between Piece and ULD is "Many to Many":
- A ULD has a list of `upid`s
- A Piece has a `uldReference` (this can change, but only one ULD at a time)

But similarly I see that the relationship between Piece and Shipment is "**Many to One**":
- A Shipment has a list of `containedPieces`
  - Why don't we have same `containedPieces` list in the ULD?
- A Piece is part of a Shipment at a given time (only one), but a Piece with the same `upid` can be part of another Shipment.
  - So the relationship between Piece and Shipment should be "**Many to Many**" I think (?)
  - I don't see any shipmentReference among the Piece properties, so if I have a piece-centric system and I need to get the Shipment of a Piece, should I get it from its transportSegment(s) -> BookingOption -> BookingOptionRequest?

Thanks in advance for your feedback

**Comment by lambertciata** [comment]
Hi,
Thanks for those feedbacks, that will be shared with the dedicated taskforce.

The "Many to Many" relationship between Piece and ULD has been extensively discussed within the taskforce and event though a Piece should be _physically_ within one ULD at a time we came to an agreement that the Many to Many relationship would cause less issues.

Having `containedPieces` on ULD as well is a valid point, it should then apply to any objects that are linked together (Object A having a `objectBs` data property and vice-versa), we'll bring up that subject in the taskforce.

UPID is by definition unique for every single Piece, so there should not be an issue there. 

You are right, it seems the Shipment of a Piece (that may be simply called `shipment`) is missing, that's a point to be added.

Thanks again
Christophe

**Comment by grichka** [comment]
You're welcome,
Looking forward to the next update of the Data Model!

**Comment by lambertciata** [comment]
This has been done on latest ontology: [Here](https://github.com/IATA-Cargo/ONE-Record/blob/master/June-2021-standard-COTB-endorsed/Data-Model/IATA-1R-DM-Ontology-vCOTB-Jun2021.ttl)
