### ISSUE TITLE
[Data Model] Company#airlinePrefix should be a String

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#85]
Hello, 

I am trying to implement the model and map data into it. I encountered an issue while trying to create a Company.
A Company has an `airlinePrefix` which is a 3 digits value like `057`. Currenly as you can see below, the airlinePrefix is an integer. 

line 3945 of the Ontology:

```
###  https://onerecord.iata.org/Company#airlinePrefix
company:airlinePrefix rdf:type owl:DatatypeProperty ;
                      rdfs:domain :Company ;
                      rdfs:range integer ;
                      rdfs:comment "IATA three-numeric airline prefix number "@en ;
                      rdfs:label "company:airlinePrefix"@en .
```

So if I want to keep my 3 digits `057` I must create a company with airlinePrefix=57 (integer), and then each time I need to print the information I have to print this integer with a formatter adding the zero to have 3 digits at the end. Is this expected behavior? Or should this integer be changed to a String in order to keep the standard 3 digits?

Thanks!

**Comment by lambertciata** [comment]
Hi,
As with #88 the datatype will be changed to string

**Comment by mskopp** [comment]
Additionally to company:airlinePrefix  there is also `waybill:waybillPrefix` and  `waybill:waybillNumber` both with a number data type.

So example AWB-Number "001-00001234" must be stored and included in JSON as waybillPrefix=1 and waybillNumber=1234, which is not the common way the industry refers to it - and it would also be inconsistent to Company#airlinePrefix if not changed to String as well.

**Comment by lambertciata** [comment]
This is noted, thanks for pointing that out @mskopp. These will be changed in the next version of the ontology

**Comment by lambertciata** [comment]
This field has been moved to Carrier object and is a string.

For backward compatibility we kept the original data property

**Comment by lambertciata** [comment]
This field has been moved to Carrier object and is a string on latest ontology [here](https://github.com/IATA-Cargo/ONE-Record/blob/master/June-2021-standard-COTB-endorsed/Data-Model/IATA-1R-DM-Ontology-vCOTB-Jun2021.ttl)

For backward compatibility we kept the original data property as integer but it is set as deprecated.
