### ISSUE TITLE
[Data Model] Ontology and logical data model do not contain the same information

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#87]
Ontology and logical data model that can be found in directories `November-2020-standard-COTB-endorsed`  and `working_draft/ontology` do not contain the same information. 
For instance, the logical data model does not correspond to what is specified by the Ontology.

How can I get an up-to-date version of the ontology and accurate logical data model? 
I know that a new release/update is planned soon, so lets use this issue to ensure that all these specifications are updated and consistent.

**Comment by andrablaj** [comment]
This is normal, as the ontology Turtle file was not yet updated according to the November logical data model. @lambertciata is working on the new version of the ontology.

**Comment by lambertciata** [comment]
New ontology has been uploaded to match the November 2020 release that is the v1.0
