### ISSUE TITLE
[Data Model] Should Branch#iataCargoAgentLocationIdentifier and Company#iataCargoAgentCode be Strings?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#88]
As specified in the current Ontology, Branch#iataCargoAgentLocationIdentifier and Company#iataCargoAgentCode properties are Integers.

However, 

- the location identifer is a 4 digits code, 
- the Cargo Agent Code is a 7 digits code

so if we use an Integer we loose the potential leading zeros, and anywhere the value must be printed, a proper formatter must be used. Should these properties be of type String instead of Integer?

**Comment by lambertciata** [comment]
Hi,

Thanks for the feedback, it echoes your comment #85 from yesterday indeed. I agree that integer does not seem to be the right data type when we expect some 0s at the beginning.

@andrablaj any thoughts on that? Is there any numerical data type that can hold codes such as "0xxx" or is string the best fit?

**Comment by grichka** [comment]
Absolutely, it is the same issue as #85 
I just try to track all problems I see "on the fly". Sorry for not grouping them.

**Comment by andrablaj** [comment]
I guess that String would be the right type for values starting with 0

**Comment by lambertciata** [comment]
Indeed, and this proposal has been validated by the Data Model taskforce, this will be modified in the next version of the ontology

**Comment by lambertciata** [comment]
This field has been moved to new object CompanyBranch and is a string on latest ontology [here](https://github.com/IATA-Cargo/ONE-Record/blob/master/June-2021-standard-COTB-endorsed/Data-Model/IATA-1R-DM-Ontology-vCOTB-Jun2021.ttl)

For backward compatibility we kept the original data property as integer but it is set as deprecated.
