### ISSUE TITLE
[Data Model] How to modelize a Booking scenario with several TransportSegments?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#89]
Hello,
I am using the Data Model released in November and relationships specified in the Ontology and logical data model.

I do not understand how to use the Data Model for the following scenario :

- The shipper wants to send goods from PEK to CDG
- The forwarder contacts the carrier (airline) to handle the transportation and creates a BookingRequest
- The carrier offers 2 options
  - One direct PEK to CDG (One TransportSegment)
  - One indirect PEK to CDG via FRA (Two TransportSegments)

How can I properly create instances of BookingRequest, BookingOption and TransportSegment for this case?
Thanks for your help!

**Comment by lambertciata** [comment]
This issue shall be rediscussed with the data model taskforce

**Comment by lambertciata** [comment]
Outcome of the workshop in 2021:
- We will implement the possibility to fill in potential segments at booking stage. This means adding some fields/common objects to account for that.
- Proposal to be made early 2022.

**Comment by lambertciata** [comment]
Current proposal:
![image](https://user-images.githubusercontent.com/58464775/151950641-760bfe53-dc6c-40dc-aa08-5859d2be9075.png)

**Comment by grichka** [comment]
I am not sure I understand this proposal.
Can you give more details on the changes made and on how to model a booking with several legs according to this proposal?

**Comment by lambertciata** [comment]
Hi,

With this proposal the scheduledLegs object (here shown as embedded in Routing) allows to identify several legs. This is inspired by the design of XFFM message.
For each leg you would have: a sequence identifier, an ID (= flight number), departure and arrival location/time.

Is that clearer?

**Comment by grichka** [comment]
So scheduledLegs is supposed to be an RDF sequence ? (an ordered list)
Then I don't understand the purpose of the class BookingSegment because BookingOption can have only one BookingSegment if I remember well.

**Comment by lambertciata** [comment]
scheduledLegs is not necessarily ordered if there is a sequence identifier, however if an RDF sequence simplifies we can have a look at how it can be transcribed in the ontology.

secheduledLegs is used to identify the intended scheduled legs at the time of booking, they can differ from actual flight legs and from my understanding they are not legally binding.
BookingSegment is used to record Departure and Arrival locations that are legally binding at AWB level. That means that BookingSegment is mandatory while scheduledLegs are optional.

**Comment by grichka** [comment]
Thanks for this explanation! The purpose of BookingSegment and scheduledLegs make much more sense to me now.

However I have some remarks/improvement proposals:
- the naming of the field "sequence" is not explicit: anybody cannot understand that a sequence is a number (it means something like a list of ordered things). I would propose to use the word "index" or "sequenceIndex" or "sequenceNumber".
- BookingSegment and scheduledLegs should include other important information including:
  - requestedDate (earliest, latest) to reach one location, asked by the customer
  - plannedDate (or estimated date) to reach one location
  - actualDate measured during transportation
