### ISSUE TITLE
missing references to item.json + transport-status.json

### ISSUE THREAD

**Issue by larspijnappel** [IATA-Cargo/ONE-Record#9]
Besides the already reported json schemas (see [rating.json](https://github.com/IATA-Cargo/ONE-Record/issues/3)  and [piece-grouping-totals.json](https://github.com/IATA-Cargo/ONE-Record/issues/4)), the following two json schemas appears to have no or incomplete references:

- product.json
  - item.json contains an undefined product attribute
- transport-status.json
  - no reference from other json schema

**Comment by andrablaj** [comment]
Thank you for the comments! We have opened a PR containgin rating.json, datetime and product.json reference fixes. We are currently checking piece-grouping-total.json.
Transport-status had no reference as it is an independent logistics object.
