### ISSUE TITLE
Question: Is there any documentation about "How to use the data model"?

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#90]
Do we have a documentation of "how to use the data model" with basic and common use cases?
Indeed interpretation of the data model could be wrong and different from one implementation to another. 
I am currently struggling to understand what data should be created (based on the data model), when, and how resources are linked together.

If such documentation exists, could it be shared? :)

**Comment by lambertciata** [comment]
Hi, 

We have worked last year on such documentation, focusing on the Industry MOP (Master Operating Plan) as basic use cases. THe document can be found here : https://github.com/IATA-Cargo/ONE-Record/blob/master/working_draft/data-model/IATA-1R-DM-ONE_Record_MOP_Mapper_20200709_for_ORTF_endorsement.xlsx

The Playbook we published last year as well covers some use cases, you can refer to slides 35+ in the following document: https://www.iata.org/contentassets/a1b5532e38bf4d6284c4bf4760646d4e/iata_one_record_implementationplaybook.pdf

Please note that these documents were published in 2020 and some changes have been made on the data model, however the overall approach remains valid.

Hope that helps
C

**Comment by grichka** [comment]
Hello Christophe,

Thanks a lot for your answer :) 

I already browsed the MOP Mapper but information in this file is not complete and not up-to-date. I think a lot of changes were made to the model since the last update of the MOP Mapper. It makes it difficult to understand how to actually use the model.

I will browse the playbook again, I think this will help me a lot (I forgot about these slides!). However I already confirm that the conceptual data model in the implementation playbook is not the same as the one published in November and not the same as what is described in the Ontology.

Anyway, thanks again for your help on it

**Comment by grichka** [comment]
Hello Christophe,

Thanks a lot for your answer :) 

I already browsed the MOP Mapper but information in this file is not complete and not up-to-date. I think a lot of changes were made to the model since the last update of the MOP Mapper. It makes it difficult to understand how to actually use the model.

I will browse the playbook again, I think this will help me a lot (I forgot about these slides!). However I already confirm that the conceptual data model in the implementation playbook is not the same as the one published in November and not the same as what is described in the Ontology.

Anyway, thanks again for your help on it

**Comment by lambertciata** [comment]
Indeed, the update of the ontology to match the 2020 Nov version is on top of my to do list :) At least these will match properly

**Comment by grichka** [comment]
Do you already know when you will release the next version?

**Comment by lambertciata** [comment]
The official version of the data model should be in Q2 2021. For the ontology I aim to have it done before the end of Feb 2021

**Comment by grichka** [comment]
Great news! Looking forward to using it
