### ISSUE TITLE
[API] API Ontology issues

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#91]
Hello, I noticed several issues in the API Ontology. Maybe @andrablaj is the best person to check the following points 😃 

------

- In the API Ontology, references to LOs are not consistent. Sometimes a logisticsObjectRef has type String, Sometimes it has type LogisticsObject. --> Only one way should be chosen among:
  1. use String for logisticsObjectRef everywhere
  2. change LogisticsObject class that appears in the API Ontology to LogisticsObjectRef. LogisticsObjectRef would only contain a LO Id for now
- here is the list of lo refs that are Strings and should maybe be changed to LogisticsObjectRef (?): 
  - AuditTrail#logisticsObjectRef
  - DelegationRequest#targetLogisticsObject
  - Notification#logisticsObjectRef
  - PatchRequest#logisticsObjectRef

------

- PatchRequest has a property `operation` which is a Set of Operations. And Operation has a property `o` which is a Set of OperationObjects as specified in the API ontology (see below). However, as specified in the standard documentation, presentations and [here](https://github.com/digibib/ls.ext/wiki/JSON-LD-PATCH), `o` should not be a Set but simply a OperationObject.

```
###  https://onerecord.iata.org/Operation
:Operation rdf:type owl:Class ;
        rdfs:subClassOf [ rdf:type owl:Restriction ;
                          owl:onProperty operation:op ;
                          owl:allValuesFrom xsd:string
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:op;
                          owl:minCardinality "1"^^xsd:nonNegativeInteger
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:op;
                          owl:maxCardinality "1"^^xsd:nonNegativeInteger
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:p ;
                          owl:allValuesFrom xsd:string
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:p;
                          owl:minCardinality "1"^^xsd:nonNegativeInteger
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:p;
                          owl:maxCardinality "1"^^xsd:nonNegativeInteger
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:o ;
                          owl:allValuesFrom <https://onerecord.iata.org/OperationObject>
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:o;
                          owl:minCardinality "1"^^xsd:nonNegativeInteger
                        ] ,
                        [ rdf:type owl:Restriction ;
                          owl:onProperty operation:o;
                          owl:minCardinality "1"^^xsd:nonNegativeInteger
                        ] ;
```

**Comment by lambertciata** [comment]
Hi, I believe ii is the best solution and is in line with Linked data principles, @andrablaj your thoughts?

**Comment by andrablaj** [comment]
Closing the issue as the API ontology and generated JSON-LD were correcte.
