### ISSUE TITLE
[API] i18n support

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#93]
Is it planned to specify how to retrieve data in different languages (internationalization)? 

Maybe a query parameter when requesting data like `?lang=en-us` (using standard language codes) would be sufficient 😄 . 

i18n support is particularly needed when getting Company information: the address could be written in Chinese or in english for example. If a Chinese Shipper provides information only with chinese characters, maybe a European company wont be able to use this information.

**Comment by andrablaj** [comment]
Closing the issue as it is now specified in the API specs draft.
