### ISSUE TITLE
[API] Create LO should return at least the URI of the created LO

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#95]
Let's assume a Shipper creates a Shipment on the Forwarder's ONE Record server.
Then the Shipper needs to update something of the Shipment. How does the Shipper know the URI of this LO to be patched?

The specification stands that the POST request to create a LO should return a 204 HTTP status code (no content). So I understand that the solution would be the Shipper subscribes to Shipments from the Forwarder and receives a notification containing data of the Shipment he has created... but I don't think this is a viable technical solution.

I would expect to at least have the Logisitics Object Ref (the LO but serialized with only its ID (and type)) in the response body of the Create LO POST HTTP Request, and a 200 http status code.

**Comment by grichka** [comment]
@andrablaj 😉

**Comment by andrablaj** [comment]
Currently, the ONE Record API specs state that the successful creation of a LO should return 201 HTTP status (Created). However, I agree with you and a `Location `header should be returned also stating the URL of the newly created LO and a 'LO-Type' header stating the type of the object. I will add this to the specs.

**Comment by grichka** [comment]
Great!
Usually in a REST APIs the newly created object is returned as a response to the POST request that creates the LO. Is there a reason to use such a Location header?

**Comment by andrablaj** [comment]
Actually, the usual behavior is to return the URI in the Location header and a 201 Created HTTP Status, per my knowledge.

**Comment by grichka** [comment]
Ok :) then nothinig to add
I will use this header on my side!

**Comment by andrablaj** [comment]
Closing the issue as the return headers were specified in the API specs draft.
