### ISSUE TITLE
[Data Model] Piece#product should be a Set

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#96]
As specified by the DM Ontology, Piece has a product property of type Product. Item also has a product property. Piece has a containedItems property that is a Set<Item>.

So the model allows a Piece to be of 1 product but a Piece can contain items that ca be of different types of products (example: black smartphones and white smarphones, in the same Piece). This makes no sense to me.

What is the purpose of Piece#product? Is this because when a Booking is made, Items are not known yet because they may not be manufactured yet?
But I think it should be possible to put items of different Products in the same Piece...

=> So should Piece#product of type Product be changed to Piece#products of type Set<Product>?

**Comment by lambertciata** [comment]
Decision from last workshop: Change will be made on next release
