### ISSUE TITLE
[Data Model] Product#characteristics should not be a LO and should be linked Product and not Company

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#97]
The current spec I found in the DM Ontology describes:
- A product has a set of Characteristics
- Charasteristic is a LO
- Charasteristic does not contain a ref to a Product

So I tried to implement the LO API for Characteristcs. I cannot POST a Characteristics LO and link it to a Product if it does not have a reference to a Product among its properties.

Now I am wondering why these characteristics should be LOs instead of simply inline objects part of a Product?

**Comment by lambertciata** [comment]
Your comment makes sense, I believe Characteristics should be a common object, not a LO. I will bring the subject to the taskforce for validation.

**Comment by lambertciata** [comment]
This topic is to be rediscussed with the data model taskforce

**Comment by lambertciata** [comment]
Decision from last workshop: Review of objects such as Characteristic will be made while reviewing all object types of the data model. To be included for next release
