### ISSUE TITLE
[API] URIs should be dash-case (or kebab-case) instead of camelCase

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#99]
It is a good practice to define URIs of REST APIs with only lowercase and hyphens "-". Camel case should be avoided. See for example this guide as a reference: [restfulapi.net](https://restfulapi.net/resource-naming/)

In the specification we have /auditTrail for example. I would propose to transform it to /audit-trail (no "s" because it is a singleton and not a collection).

Also a full review would be great to follow this recommendation everywhere 😃

**Comment by andrablaj** [comment]
Solved [here](https://github.com/IATA-Cargo/ONE-Record/commit/fac0f75e1853519b5dd182840664984f4c746dac)
